/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 58
#define LARGE_STATE_COUNT 25
#define SYMBOL_COUNT 70
#define ALIAS_COUNT 0
#define TOKEN_COUNT 57
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_RBRACK = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  sym_identifier = 7,
  sym_path = 8,
  anon_sym_EQ = 9,
  anon_sym_DOT_EQ = 10,
  anon_sym_COLON_EQ = 11,
  anon_sym_TILDE = 12,
  anon_sym_DASH_DASH = 13,
  anon_sym_GT_GT = 14,
  anon_sym_LT_LT = 15,
  anon_sym_PIPE_GT = 16,
  anon_sym_LT_PIPE = 17,
  anon_sym_COLON_COLON = 18,
  anon_sym_DOT_DOT = 19,
  anon_sym_GT_EQ = 20,
  anon_sym_LT_EQ = 21,
  anon_sym_EQ_EQ = 22,
  anon_sym_QMARK_GT = 23,
  anon_sym_LT_QMARK = 24,
  anon_sym_LT_QMARK_GT = 25,
  anon_sym_DASH_GT = 26,
  anon_sym_LT_DASH = 27,
  anon_sym_LT_DASH_GT = 28,
  anon_sym_PLUS = 29,
  anon_sym_DASH = 30,
  anon_sym_STAR = 31,
  anon_sym_SLASH = 32,
  anon_sym_COLON = 33,
  anon_sym_PIPE = 34,
  anon_sym_PERCENT = 35,
  anon_sym_DOT = 36,
  anon_sym_AT = 37,
  anon_sym_DOLLAR = 38,
  anon_sym_AMP = 39,
  anon_sym_BQUOTE = 40,
  anon_sym_BANG = 41,
  sym_const_number = 42,
  anon_sym_DQUOTE = 43,
  aux_sym_const_string_token1 = 44,
  anon_sym_COMMA_COMMA_COMMA = 45,
  anon_sym_LF = 46,
  anon_sym_LF_COMMA_COMMA_COMMA = 47,
  sym_paragrapth_head = 48,
  sym_paragrapth_content = 49,
  anon_sym_CARET_ = 50,
  aux_sym_cat_string_token1 = 51,
  aux_sym_cat_string_token2 = 52,
  anon_sym__ = 53,
  aux_sym_cat_string_token3 = 54,
  anon_sym__CARET = 55,
  sym_comment = 56,
  sym_source_file = 57,
  sym_pair = 58,
  sym_list = 59,
  sym_curly_list = 60,
  sym_group = 61,
  sym_binary_expression = 62,
  sym_unary_expression = 63,
  sym_const_value = 64,
  sym_const_string = 65,
  sym_paragrapth = 66,
  sym_cat_string = 67,
  aux_sym_paragrapth_repeat1 = 68,
  aux_sym_cat_string_repeat1 = 69,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_identifier] = "identifier",
  [sym_path] = "path",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT_EQ] = ".=",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_TILDE] = "~",
  [anon_sym_DASH_DASH] = "--",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_PIPE_GT] = "|>",
  [anon_sym_LT_PIPE] = "<|",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_QMARK_GT] = "\?>",
  [anon_sym_LT_QMARK] = "<\?",
  [anon_sym_LT_QMARK_GT] = "<\?>",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_LT_DASH_GT] = "<->",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "|",
  [anon_sym_PERCENT] = "%",
  [anon_sym_DOT] = ".",
  [anon_sym_AT] = "@",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_AMP] = "&",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_BANG] = "!",
  [sym_const_number] = "const_number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_const_string_token1] = "const_string_token1",
  [anon_sym_COMMA_COMMA_COMMA] = ",,,",
  [anon_sym_LF] = "\n",
  [anon_sym_LF_COMMA_COMMA_COMMA] = "\n,,,",
  [sym_paragrapth_head] = "paragrapth_head",
  [sym_paragrapth_content] = "paragrapth_content",
  [anon_sym_CARET_] = "^_",
  [aux_sym_cat_string_token1] = "cat_string_token1",
  [aux_sym_cat_string_token2] = "cat_string_token2",
  [anon_sym__] = "_",
  [aux_sym_cat_string_token3] = "cat_string_token3",
  [anon_sym__CARET] = "_^",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_pair] = "pair",
  [sym_list] = "list",
  [sym_curly_list] = "curly_list",
  [sym_group] = "group",
  [sym_binary_expression] = "binary_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_const_value] = "const_value",
  [sym_const_string] = "const_string",
  [sym_paragrapth] = "paragrapth",
  [sym_cat_string] = "cat_string",
  [aux_sym_paragrapth_repeat1] = "paragrapth_repeat1",
  [aux_sym_cat_string_repeat1] = "cat_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_identifier] = sym_identifier,
  [sym_path] = sym_path,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT_EQ] = anon_sym_DOT_EQ,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_PIPE_GT] = anon_sym_PIPE_GT,
  [anon_sym_LT_PIPE] = anon_sym_LT_PIPE,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_QMARK_GT] = anon_sym_QMARK_GT,
  [anon_sym_LT_QMARK] = anon_sym_LT_QMARK,
  [anon_sym_LT_QMARK_GT] = anon_sym_LT_QMARK_GT,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_LT_DASH_GT] = anon_sym_LT_DASH_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_BANG] = anon_sym_BANG,
  [sym_const_number] = sym_const_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_const_string_token1] = aux_sym_const_string_token1,
  [anon_sym_COMMA_COMMA_COMMA] = anon_sym_COMMA_COMMA_COMMA,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LF_COMMA_COMMA_COMMA] = anon_sym_LF_COMMA_COMMA_COMMA,
  [sym_paragrapth_head] = sym_paragrapth_head,
  [sym_paragrapth_content] = sym_paragrapth_content,
  [anon_sym_CARET_] = anon_sym_CARET_,
  [aux_sym_cat_string_token1] = aux_sym_cat_string_token1,
  [aux_sym_cat_string_token2] = aux_sym_cat_string_token2,
  [anon_sym__] = anon_sym__,
  [aux_sym_cat_string_token3] = aux_sym_cat_string_token3,
  [anon_sym__CARET] = anon_sym__CARET,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_pair] = sym_pair,
  [sym_list] = sym_list,
  [sym_curly_list] = sym_curly_list,
  [sym_group] = sym_group,
  [sym_binary_expression] = sym_binary_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_const_value] = sym_const_value,
  [sym_const_string] = sym_const_string,
  [sym_paragrapth] = sym_paragrapth,
  [sym_cat_string] = sym_cat_string,
  [aux_sym_paragrapth_repeat1] = aux_sym_paragrapth_repeat1,
  [aux_sym_cat_string_repeat1] = aux_sym_cat_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_QMARK_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym_const_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_const_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA_COMMA_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF_COMMA_COMMA_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_paragrapth_head] = {
    .visible = true,
    .named = true,
  },
  [sym_paragrapth_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_CARET_] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_cat_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cat_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_cat_string_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym__CARET] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_curly_list] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_const_value] = {
    .visible = true,
    .named = true,
  },
  [sym_const_string] = {
    .visible = true,
    .named = true,
  },
  [sym_paragrapth] = {
    .visible = true,
    .named = true,
  },
  [sym_cat_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_paragrapth_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cat_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
};

const TSCharacterRange sym_path_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '('}, {'*', '+'}, {'-', ':'}, {'<', '\\'}, {'^', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '\n', 1,
        '!', 57,
        '"', 59,
        '$', 54,
        '%', 51,
        '&', 55,
        '(', 21,
        ')', 22,
        '*', 47,
        '+', 45,
        ',', 6,
        '-', 46,
        '.', 52,
        '/', 48,
        ':', 49,
        ';', 85,
        '<', 7,
        '=', 25,
        '>', 11,
        '?', 12,
        '@', 53,
        '[', 17,
        ']', 18,
        '^', 13,
        '_', 80,
        '`', 56,
        '{', 19,
        '|', 50,
        '}', 20,
        '~', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 1,
        '!', 57,
        '"', 59,
        '$', 54,
        '%', 51,
        '&', 55,
        '(', 21,
        ')', 22,
        '*', 47,
        '+', 45,
        ',', 6,
        '-', 46,
        '.', 52,
        '/', 48,
        ':', 49,
        ';', 85,
        '<', 7,
        '=', 25,
        '>', 11,
        '?', 12,
        '@', 53,
        '[', 17,
        ']', 18,
        '^', 13,
        '_', 80,
        '`', 56,
        '{', 19,
        '|', 50,
        '}', 20,
        '~', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(68);
      if (lookahead == ';') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(69);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(70);
      if (lookahead == ';') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(71);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == ';') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == ',') ADVANCE(63);
      END_STATE();
    case 6:
      if (lookahead == ',') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(37);
      if (lookahead == '?') ADVANCE(40);
      if (lookahead == '|') ADVANCE(33);
      END_STATE();
    case 8:
      if (lookahead == ';') ADVANCE(85);
      if (lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) SKIP(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(76);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 9:
      if (lookahead == ';') ADVANCE(79);
      if (lookahead == '_') ADVANCE(80);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(78);
      if (lookahead != 0) ADVANCE(77);
      END_STATE();
    case 10:
      if (lookahead == ';') ADVANCE(83);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '^') ADVANCE(81);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(36);
      if (lookahead == '>') ADVANCE(30);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(39);
      END_STATE();
    case 13:
      if (lookahead == '_') ADVANCE(75);
      END_STATE();
    case 14:
      if ((!eof && set_contains(sym_path_character_set_1, 9, lookahead))) ADVANCE(24);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '!', 57,
        '"', 59,
        '$', 54,
        '%', 51,
        '&', 55,
        '(', 21,
        ')', 22,
        '*', 47,
        '+', 45,
        ',', 6,
        '-', 46,
        '.', 52,
        '/', 48,
        ':', 49,
        ';', 85,
        '<', 7,
        '=', 25,
        '>', 11,
        '?', 12,
        '@', 53,
        '[', 17,
        ']', 18,
        '^', 13,
        '`', 56,
        '{', 19,
        '|', 50,
        '}', 20,
        '~', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) SKIP(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_path);
      if (lookahead == '/') ADVANCE(24);
      if ((!eof && set_contains(sym_path_character_set_1, 9, lookahead))) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DOT_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_PIPE_GT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT_PIPE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_QMARK_GT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LT_QMARK);
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT_QMARK_GT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      if (lookahead == '>') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LT_DASH_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '>') ADVANCE(42);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if ((!eof && set_contains(sym_path_character_set_1, 9, lookahead))) ADVANCE(24);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(34);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '>') ADVANCE(32);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_const_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_const_string_token1);
      if (lookahead == '\n') ADVANCE(62);
      if (lookahead == '"') ADVANCE(85);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_const_string_token1);
      if (lookahead == ';') ADVANCE(60);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_const_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_COMMA_COMMA_COMMA);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LF_COMMA_COMMA_COMMA);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(74);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_paragrapth_head);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(74);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_paragrapth_head);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_paragrapth_content);
      if (lookahead == '\n') ADVANCE(68);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == ';') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(69);
      if (('+' <= lookahead && lookahead <= '-') ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_paragrapth_content);
      if (lookahead == '\n') ADVANCE(68);
      if (lookahead == ';') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(69);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_paragrapth_content);
      if (lookahead == '\n') ADVANCE(70);
      if (lookahead == ',') ADVANCE(73);
      if (lookahead == ';') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(71);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_paragrapth_content);
      if (lookahead == '\n') ADVANCE(70);
      if (lookahead == ';') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(71);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_paragrapth_content);
      if (lookahead == ',') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(74);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_paragrapth_content);
      if (lookahead == ',') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_paragrapth_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_CARET_);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_cat_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_cat_string_token2);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_cat_string_token2);
      if (lookahead == ';') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '_') ADVANCE(77);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_cat_string_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym__);
      if (lookahead == '^') ADVANCE(84);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_cat_string_token3);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_cat_string_token3);
      if (lookahead == ';') ADVANCE(83);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '^') ADVANCE(81);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_cat_string_token3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym__CARET);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 15},
  [6] = {.lex_state = 15},
  [7] = {.lex_state = 15},
  [8] = {.lex_state = 15},
  [9] = {.lex_state = 15},
  [10] = {.lex_state = 15},
  [11] = {.lex_state = 15},
  [12] = {.lex_state = 15},
  [13] = {.lex_state = 15},
  [14] = {.lex_state = 15},
  [15] = {.lex_state = 15},
  [16] = {.lex_state = 15},
  [17] = {.lex_state = 15},
  [18] = {.lex_state = 15},
  [19] = {.lex_state = 15},
  [20] = {.lex_state = 15},
  [21] = {.lex_state = 15},
  [22] = {.lex_state = 15},
  [23] = {.lex_state = 15},
  [24] = {.lex_state = 15},
  [25] = {.lex_state = 15},
  [26] = {.lex_state = 15},
  [27] = {.lex_state = 15},
  [28] = {.lex_state = 15},
  [29] = {.lex_state = 15},
  [30] = {.lex_state = 15},
  [31] = {.lex_state = 15},
  [32] = {.lex_state = 15},
  [33] = {.lex_state = 15},
  [34] = {.lex_state = 15},
  [35] = {.lex_state = 9},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 9},
  [39] = {.lex_state = 9},
  [40] = {.lex_state = 9},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 9},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 61},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 10},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_path] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT_EQ] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_PIPE_GT] = ACTIONS(1),
    [anon_sym_LT_PIPE] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_QMARK_GT] = ACTIONS(1),
    [anon_sym_LT_QMARK] = ACTIONS(1),
    [anon_sym_LT_QMARK_GT] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_LT_DASH_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [sym_const_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(1),
    [anon_sym_LF_COMMA_COMMA_COMMA] = ACTIONS(1),
    [anon_sym_CARET_] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym__CARET] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(52),
    [sym_pair] = STATE(51),
    [sym_list] = STATE(2),
    [sym_curly_list] = STATE(2),
    [sym_group] = STATE(2),
    [sym_binary_expression] = STATE(2),
    [sym_unary_expression] = STATE(2),
    [sym_const_value] = STATE(2),
    [sym_const_string] = STATE(5),
    [sym_paragrapth] = STATE(5),
    [sym_cat_string] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [sym_path] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_DOLLAR] = ACTIONS(15),
    [anon_sym_AMP] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [sym_const_number] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(21),
    [anon_sym_CARET_] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_pair] = STATE(41),
    [sym_list] = STATE(2),
    [sym_curly_list] = STATE(2),
    [sym_group] = STATE(2),
    [sym_binary_expression] = STATE(2),
    [sym_unary_expression] = STATE(2),
    [sym_const_value] = STATE(2),
    [sym_const_string] = STATE(5),
    [sym_paragrapth] = STATE(5),
    [sym_cat_string] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_RBRACK] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(25),
    [sym_identifier] = ACTIONS(13),
    [sym_path] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_DOT_EQ] = ACTIONS(29),
    [anon_sym_COLON_EQ] = ACTIONS(29),
    [anon_sym_TILDE] = ACTIONS(29),
    [anon_sym_DASH_DASH] = ACTIONS(29),
    [anon_sym_GT_GT] = ACTIONS(31),
    [anon_sym_LT_LT] = ACTIONS(31),
    [anon_sym_PIPE_GT] = ACTIONS(31),
    [anon_sym_LT_PIPE] = ACTIONS(31),
    [anon_sym_COLON_COLON] = ACTIONS(31),
    [anon_sym_DOT_DOT] = ACTIONS(31),
    [anon_sym_GT_EQ] = ACTIONS(31),
    [anon_sym_LT_EQ] = ACTIONS(31),
    [anon_sym_EQ_EQ] = ACTIONS(31),
    [anon_sym_QMARK_GT] = ACTIONS(31),
    [anon_sym_LT_QMARK] = ACTIONS(33),
    [anon_sym_LT_QMARK_GT] = ACTIONS(31),
    [anon_sym_DASH_GT] = ACTIONS(31),
    [anon_sym_LT_DASH] = ACTIONS(33),
    [anon_sym_LT_DASH_GT] = ACTIONS(31),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(37),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(41),
    [anon_sym_COLON] = ACTIONS(43),
    [anon_sym_PIPE] = ACTIONS(43),
    [anon_sym_PERCENT] = ACTIONS(45),
    [anon_sym_DOT] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_DOLLAR] = ACTIONS(15),
    [anon_sym_AMP] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [sym_const_number] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(21),
    [anon_sym_CARET_] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [ts_builtin_sym_end] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [anon_sym_RBRACK] = ACTIONS(49),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(49),
    [anon_sym_RPAREN] = ACTIONS(49),
    [sym_identifier] = ACTIONS(49),
    [sym_path] = ACTIONS(49),
    [anon_sym_EQ] = ACTIONS(51),
    [anon_sym_DOT_EQ] = ACTIONS(49),
    [anon_sym_COLON_EQ] = ACTIONS(49),
    [anon_sym_TILDE] = ACTIONS(49),
    [anon_sym_DASH_DASH] = ACTIONS(49),
    [anon_sym_GT_GT] = ACTIONS(49),
    [anon_sym_LT_LT] = ACTIONS(49),
    [anon_sym_PIPE_GT] = ACTIONS(49),
    [anon_sym_LT_PIPE] = ACTIONS(49),
    [anon_sym_COLON_COLON] = ACTIONS(49),
    [anon_sym_DOT_DOT] = ACTIONS(49),
    [anon_sym_GT_EQ] = ACTIONS(49),
    [anon_sym_LT_EQ] = ACTIONS(49),
    [anon_sym_EQ_EQ] = ACTIONS(49),
    [anon_sym_QMARK_GT] = ACTIONS(49),
    [anon_sym_LT_QMARK] = ACTIONS(51),
    [anon_sym_LT_QMARK_GT] = ACTIONS(49),
    [anon_sym_DASH_GT] = ACTIONS(49),
    [anon_sym_LT_DASH] = ACTIONS(51),
    [anon_sym_LT_DASH_GT] = ACTIONS(49),
    [anon_sym_PLUS] = ACTIONS(49),
    [anon_sym_DASH] = ACTIONS(51),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym_SLASH] = ACTIONS(51),
    [anon_sym_COLON] = ACTIONS(51),
    [anon_sym_PIPE] = ACTIONS(51),
    [anon_sym_PERCENT] = ACTIONS(49),
    [anon_sym_DOT] = ACTIONS(51),
    [anon_sym_AT] = ACTIONS(49),
    [anon_sym_DOLLAR] = ACTIONS(49),
    [anon_sym_AMP] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_BANG] = ACTIONS(49),
    [sym_const_number] = ACTIONS(49),
    [anon_sym_DQUOTE] = ACTIONS(49),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(49),
    [anon_sym_CARET_] = ACTIONS(49),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(53),
    [anon_sym_RBRACK] = ACTIONS(53),
    [anon_sym_LBRACE] = ACTIONS(53),
    [anon_sym_RBRACE] = ACTIONS(53),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_RPAREN] = ACTIONS(53),
    [sym_identifier] = ACTIONS(53),
    [sym_path] = ACTIONS(53),
    [anon_sym_EQ] = ACTIONS(55),
    [anon_sym_DOT_EQ] = ACTIONS(53),
    [anon_sym_COLON_EQ] = ACTIONS(53),
    [anon_sym_TILDE] = ACTIONS(53),
    [anon_sym_DASH_DASH] = ACTIONS(53),
    [anon_sym_GT_GT] = ACTIONS(53),
    [anon_sym_LT_LT] = ACTIONS(53),
    [anon_sym_PIPE_GT] = ACTIONS(53),
    [anon_sym_LT_PIPE] = ACTIONS(53),
    [anon_sym_COLON_COLON] = ACTIONS(53),
    [anon_sym_DOT_DOT] = ACTIONS(53),
    [anon_sym_GT_EQ] = ACTIONS(53),
    [anon_sym_LT_EQ] = ACTIONS(53),
    [anon_sym_EQ_EQ] = ACTIONS(53),
    [anon_sym_QMARK_GT] = ACTIONS(53),
    [anon_sym_LT_QMARK] = ACTIONS(55),
    [anon_sym_LT_QMARK_GT] = ACTIONS(53),
    [anon_sym_DASH_GT] = ACTIONS(53),
    [anon_sym_LT_DASH] = ACTIONS(55),
    [anon_sym_LT_DASH_GT] = ACTIONS(53),
    [anon_sym_PLUS] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym_SLASH] = ACTIONS(55),
    [anon_sym_COLON] = ACTIONS(55),
    [anon_sym_PIPE] = ACTIONS(55),
    [anon_sym_PERCENT] = ACTIONS(53),
    [anon_sym_DOT] = ACTIONS(55),
    [anon_sym_AT] = ACTIONS(53),
    [anon_sym_DOLLAR] = ACTIONS(53),
    [anon_sym_AMP] = ACTIONS(53),
    [anon_sym_BQUOTE] = ACTIONS(53),
    [anon_sym_BANG] = ACTIONS(53),
    [sym_const_number] = ACTIONS(53),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(53),
    [anon_sym_CARET_] = ACTIONS(53),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(57),
    [anon_sym_LBRACK] = ACTIONS(57),
    [anon_sym_RBRACK] = ACTIONS(57),
    [anon_sym_LBRACE] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(57),
    [anon_sym_LPAREN] = ACTIONS(57),
    [anon_sym_RPAREN] = ACTIONS(57),
    [sym_identifier] = ACTIONS(57),
    [sym_path] = ACTIONS(57),
    [anon_sym_EQ] = ACTIONS(59),
    [anon_sym_DOT_EQ] = ACTIONS(57),
    [anon_sym_COLON_EQ] = ACTIONS(57),
    [anon_sym_TILDE] = ACTIONS(57),
    [anon_sym_DASH_DASH] = ACTIONS(57),
    [anon_sym_GT_GT] = ACTIONS(57),
    [anon_sym_LT_LT] = ACTIONS(57),
    [anon_sym_PIPE_GT] = ACTIONS(57),
    [anon_sym_LT_PIPE] = ACTIONS(57),
    [anon_sym_COLON_COLON] = ACTIONS(57),
    [anon_sym_DOT_DOT] = ACTIONS(57),
    [anon_sym_GT_EQ] = ACTIONS(57),
    [anon_sym_LT_EQ] = ACTIONS(57),
    [anon_sym_EQ_EQ] = ACTIONS(57),
    [anon_sym_QMARK_GT] = ACTIONS(57),
    [anon_sym_LT_QMARK] = ACTIONS(59),
    [anon_sym_LT_QMARK_GT] = ACTIONS(57),
    [anon_sym_DASH_GT] = ACTIONS(57),
    [anon_sym_LT_DASH] = ACTIONS(59),
    [anon_sym_LT_DASH_GT] = ACTIONS(57),
    [anon_sym_PLUS] = ACTIONS(57),
    [anon_sym_DASH] = ACTIONS(59),
    [anon_sym_STAR] = ACTIONS(57),
    [anon_sym_SLASH] = ACTIONS(59),
    [anon_sym_COLON] = ACTIONS(59),
    [anon_sym_PIPE] = ACTIONS(59),
    [anon_sym_PERCENT] = ACTIONS(57),
    [anon_sym_DOT] = ACTIONS(59),
    [anon_sym_AT] = ACTIONS(57),
    [anon_sym_DOLLAR] = ACTIONS(57),
    [anon_sym_AMP] = ACTIONS(57),
    [anon_sym_BQUOTE] = ACTIONS(57),
    [anon_sym_BANG] = ACTIONS(57),
    [sym_const_number] = ACTIONS(57),
    [anon_sym_DQUOTE] = ACTIONS(57),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(57),
    [anon_sym_CARET_] = ACTIONS(57),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(61),
    [anon_sym_LPAREN] = ACTIONS(61),
    [anon_sym_RPAREN] = ACTIONS(61),
    [sym_identifier] = ACTIONS(61),
    [sym_path] = ACTIONS(61),
    [anon_sym_EQ] = ACTIONS(63),
    [anon_sym_DOT_EQ] = ACTIONS(61),
    [anon_sym_COLON_EQ] = ACTIONS(61),
    [anon_sym_TILDE] = ACTIONS(61),
    [anon_sym_DASH_DASH] = ACTIONS(61),
    [anon_sym_GT_GT] = ACTIONS(61),
    [anon_sym_LT_LT] = ACTIONS(61),
    [anon_sym_PIPE_GT] = ACTIONS(61),
    [anon_sym_LT_PIPE] = ACTIONS(61),
    [anon_sym_COLON_COLON] = ACTIONS(61),
    [anon_sym_DOT_DOT] = ACTIONS(61),
    [anon_sym_GT_EQ] = ACTIONS(61),
    [anon_sym_LT_EQ] = ACTIONS(61),
    [anon_sym_EQ_EQ] = ACTIONS(61),
    [anon_sym_QMARK_GT] = ACTIONS(61),
    [anon_sym_LT_QMARK] = ACTIONS(63),
    [anon_sym_LT_QMARK_GT] = ACTIONS(61),
    [anon_sym_DASH_GT] = ACTIONS(61),
    [anon_sym_LT_DASH] = ACTIONS(63),
    [anon_sym_LT_DASH_GT] = ACTIONS(61),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(63),
    [anon_sym_STAR] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [anon_sym_COLON] = ACTIONS(63),
    [anon_sym_PIPE] = ACTIONS(63),
    [anon_sym_PERCENT] = ACTIONS(61),
    [anon_sym_DOT] = ACTIONS(63),
    [anon_sym_AT] = ACTIONS(61),
    [anon_sym_DOLLAR] = ACTIONS(61),
    [anon_sym_AMP] = ACTIONS(61),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_BANG] = ACTIONS(61),
    [sym_const_number] = ACTIONS(61),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(61),
    [anon_sym_CARET_] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(65),
    [anon_sym_RBRACK] = ACTIONS(65),
    [anon_sym_LBRACE] = ACTIONS(65),
    [anon_sym_RBRACE] = ACTIONS(65),
    [anon_sym_LPAREN] = ACTIONS(65),
    [anon_sym_RPAREN] = ACTIONS(65),
    [sym_identifier] = ACTIONS(65),
    [sym_path] = ACTIONS(65),
    [anon_sym_EQ] = ACTIONS(67),
    [anon_sym_DOT_EQ] = ACTIONS(65),
    [anon_sym_COLON_EQ] = ACTIONS(65),
    [anon_sym_TILDE] = ACTIONS(65),
    [anon_sym_DASH_DASH] = ACTIONS(65),
    [anon_sym_GT_GT] = ACTIONS(65),
    [anon_sym_LT_LT] = ACTIONS(65),
    [anon_sym_PIPE_GT] = ACTIONS(65),
    [anon_sym_LT_PIPE] = ACTIONS(65),
    [anon_sym_COLON_COLON] = ACTIONS(65),
    [anon_sym_DOT_DOT] = ACTIONS(65),
    [anon_sym_GT_EQ] = ACTIONS(65),
    [anon_sym_LT_EQ] = ACTIONS(65),
    [anon_sym_EQ_EQ] = ACTIONS(65),
    [anon_sym_QMARK_GT] = ACTIONS(65),
    [anon_sym_LT_QMARK] = ACTIONS(67),
    [anon_sym_LT_QMARK_GT] = ACTIONS(65),
    [anon_sym_DASH_GT] = ACTIONS(65),
    [anon_sym_LT_DASH] = ACTIONS(67),
    [anon_sym_LT_DASH_GT] = ACTIONS(65),
    [anon_sym_PLUS] = ACTIONS(65),
    [anon_sym_DASH] = ACTIONS(67),
    [anon_sym_STAR] = ACTIONS(65),
    [anon_sym_SLASH] = ACTIONS(67),
    [anon_sym_COLON] = ACTIONS(67),
    [anon_sym_PIPE] = ACTIONS(67),
    [anon_sym_PERCENT] = ACTIONS(65),
    [anon_sym_DOT] = ACTIONS(67),
    [anon_sym_AT] = ACTIONS(65),
    [anon_sym_DOLLAR] = ACTIONS(65),
    [anon_sym_AMP] = ACTIONS(65),
    [anon_sym_BQUOTE] = ACTIONS(65),
    [anon_sym_BANG] = ACTIONS(65),
    [sym_const_number] = ACTIONS(65),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(65),
    [anon_sym_CARET_] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [anon_sym_LBRACK] = ACTIONS(69),
    [anon_sym_RBRACK] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(69),
    [anon_sym_RBRACE] = ACTIONS(69),
    [anon_sym_LPAREN] = ACTIONS(69),
    [anon_sym_RPAREN] = ACTIONS(69),
    [sym_identifier] = ACTIONS(69),
    [sym_path] = ACTIONS(69),
    [anon_sym_EQ] = ACTIONS(71),
    [anon_sym_DOT_EQ] = ACTIONS(69),
    [anon_sym_COLON_EQ] = ACTIONS(69),
    [anon_sym_TILDE] = ACTIONS(69),
    [anon_sym_DASH_DASH] = ACTIONS(69),
    [anon_sym_GT_GT] = ACTIONS(69),
    [anon_sym_LT_LT] = ACTIONS(69),
    [anon_sym_PIPE_GT] = ACTIONS(69),
    [anon_sym_LT_PIPE] = ACTIONS(69),
    [anon_sym_COLON_COLON] = ACTIONS(69),
    [anon_sym_DOT_DOT] = ACTIONS(69),
    [anon_sym_GT_EQ] = ACTIONS(69),
    [anon_sym_LT_EQ] = ACTIONS(69),
    [anon_sym_EQ_EQ] = ACTIONS(69),
    [anon_sym_QMARK_GT] = ACTIONS(69),
    [anon_sym_LT_QMARK] = ACTIONS(71),
    [anon_sym_LT_QMARK_GT] = ACTIONS(69),
    [anon_sym_DASH_GT] = ACTIONS(69),
    [anon_sym_LT_DASH] = ACTIONS(71),
    [anon_sym_LT_DASH_GT] = ACTIONS(69),
    [anon_sym_PLUS] = ACTIONS(69),
    [anon_sym_DASH] = ACTIONS(71),
    [anon_sym_STAR] = ACTIONS(69),
    [anon_sym_SLASH] = ACTIONS(71),
    [anon_sym_COLON] = ACTIONS(71),
    [anon_sym_PIPE] = ACTIONS(71),
    [anon_sym_PERCENT] = ACTIONS(69),
    [anon_sym_DOT] = ACTIONS(71),
    [anon_sym_AT] = ACTIONS(69),
    [anon_sym_DOLLAR] = ACTIONS(69),
    [anon_sym_AMP] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(69),
    [anon_sym_BANG] = ACTIONS(69),
    [sym_const_number] = ACTIONS(69),
    [anon_sym_DQUOTE] = ACTIONS(69),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(69),
    [anon_sym_CARET_] = ACTIONS(69),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(73),
    [anon_sym_RBRACK] = ACTIONS(73),
    [anon_sym_LBRACE] = ACTIONS(73),
    [anon_sym_RBRACE] = ACTIONS(73),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_RPAREN] = ACTIONS(73),
    [sym_identifier] = ACTIONS(73),
    [sym_path] = ACTIONS(73),
    [anon_sym_EQ] = ACTIONS(75),
    [anon_sym_DOT_EQ] = ACTIONS(73),
    [anon_sym_COLON_EQ] = ACTIONS(73),
    [anon_sym_TILDE] = ACTIONS(73),
    [anon_sym_DASH_DASH] = ACTIONS(73),
    [anon_sym_GT_GT] = ACTIONS(73),
    [anon_sym_LT_LT] = ACTIONS(73),
    [anon_sym_PIPE_GT] = ACTIONS(73),
    [anon_sym_LT_PIPE] = ACTIONS(73),
    [anon_sym_COLON_COLON] = ACTIONS(73),
    [anon_sym_DOT_DOT] = ACTIONS(73),
    [anon_sym_GT_EQ] = ACTIONS(73),
    [anon_sym_LT_EQ] = ACTIONS(73),
    [anon_sym_EQ_EQ] = ACTIONS(73),
    [anon_sym_QMARK_GT] = ACTIONS(73),
    [anon_sym_LT_QMARK] = ACTIONS(75),
    [anon_sym_LT_QMARK_GT] = ACTIONS(73),
    [anon_sym_DASH_GT] = ACTIONS(73),
    [anon_sym_LT_DASH] = ACTIONS(75),
    [anon_sym_LT_DASH_GT] = ACTIONS(73),
    [anon_sym_PLUS] = ACTIONS(73),
    [anon_sym_DASH] = ACTIONS(75),
    [anon_sym_STAR] = ACTIONS(73),
    [anon_sym_SLASH] = ACTIONS(75),
    [anon_sym_COLON] = ACTIONS(75),
    [anon_sym_PIPE] = ACTIONS(75),
    [anon_sym_PERCENT] = ACTIONS(73),
    [anon_sym_DOT] = ACTIONS(75),
    [anon_sym_AT] = ACTIONS(73),
    [anon_sym_DOLLAR] = ACTIONS(73),
    [anon_sym_AMP] = ACTIONS(73),
    [anon_sym_BQUOTE] = ACTIONS(73),
    [anon_sym_BANG] = ACTIONS(73),
    [sym_const_number] = ACTIONS(73),
    [anon_sym_DQUOTE] = ACTIONS(73),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(73),
    [anon_sym_CARET_] = ACTIONS(73),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(77),
    [anon_sym_LBRACK] = ACTIONS(77),
    [anon_sym_RBRACK] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(77),
    [anon_sym_RBRACE] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(77),
    [anon_sym_RPAREN] = ACTIONS(77),
    [sym_identifier] = ACTIONS(77),
    [sym_path] = ACTIONS(77),
    [anon_sym_EQ] = ACTIONS(79),
    [anon_sym_DOT_EQ] = ACTIONS(77),
    [anon_sym_COLON_EQ] = ACTIONS(77),
    [anon_sym_TILDE] = ACTIONS(77),
    [anon_sym_DASH_DASH] = ACTIONS(77),
    [anon_sym_GT_GT] = ACTIONS(77),
    [anon_sym_LT_LT] = ACTIONS(77),
    [anon_sym_PIPE_GT] = ACTIONS(77),
    [anon_sym_LT_PIPE] = ACTIONS(77),
    [anon_sym_COLON_COLON] = ACTIONS(77),
    [anon_sym_DOT_DOT] = ACTIONS(77),
    [anon_sym_GT_EQ] = ACTIONS(77),
    [anon_sym_LT_EQ] = ACTIONS(77),
    [anon_sym_EQ_EQ] = ACTIONS(77),
    [anon_sym_QMARK_GT] = ACTIONS(77),
    [anon_sym_LT_QMARK] = ACTIONS(79),
    [anon_sym_LT_QMARK_GT] = ACTIONS(77),
    [anon_sym_DASH_GT] = ACTIONS(77),
    [anon_sym_LT_DASH] = ACTIONS(79),
    [anon_sym_LT_DASH_GT] = ACTIONS(77),
    [anon_sym_PLUS] = ACTIONS(77),
    [anon_sym_DASH] = ACTIONS(79),
    [anon_sym_STAR] = ACTIONS(77),
    [anon_sym_SLASH] = ACTIONS(79),
    [anon_sym_COLON] = ACTIONS(79),
    [anon_sym_PIPE] = ACTIONS(79),
    [anon_sym_PERCENT] = ACTIONS(77),
    [anon_sym_DOT] = ACTIONS(79),
    [anon_sym_AT] = ACTIONS(77),
    [anon_sym_DOLLAR] = ACTIONS(77),
    [anon_sym_AMP] = ACTIONS(77),
    [anon_sym_BQUOTE] = ACTIONS(77),
    [anon_sym_BANG] = ACTIONS(77),
    [sym_const_number] = ACTIONS(77),
    [anon_sym_DQUOTE] = ACTIONS(77),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(77),
    [anon_sym_CARET_] = ACTIONS(77),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(81),
    [sym_identifier] = ACTIONS(81),
    [sym_path] = ACTIONS(81),
    [anon_sym_EQ] = ACTIONS(83),
    [anon_sym_DOT_EQ] = ACTIONS(81),
    [anon_sym_COLON_EQ] = ACTIONS(81),
    [anon_sym_TILDE] = ACTIONS(81),
    [anon_sym_DASH_DASH] = ACTIONS(81),
    [anon_sym_GT_GT] = ACTIONS(81),
    [anon_sym_LT_LT] = ACTIONS(81),
    [anon_sym_PIPE_GT] = ACTIONS(81),
    [anon_sym_LT_PIPE] = ACTIONS(81),
    [anon_sym_COLON_COLON] = ACTIONS(81),
    [anon_sym_DOT_DOT] = ACTIONS(81),
    [anon_sym_GT_EQ] = ACTIONS(81),
    [anon_sym_LT_EQ] = ACTIONS(81),
    [anon_sym_EQ_EQ] = ACTIONS(81),
    [anon_sym_QMARK_GT] = ACTIONS(81),
    [anon_sym_LT_QMARK] = ACTIONS(83),
    [anon_sym_LT_QMARK_GT] = ACTIONS(81),
    [anon_sym_DASH_GT] = ACTIONS(81),
    [anon_sym_LT_DASH] = ACTIONS(83),
    [anon_sym_LT_DASH_GT] = ACTIONS(81),
    [anon_sym_PLUS] = ACTIONS(81),
    [anon_sym_DASH] = ACTIONS(83),
    [anon_sym_STAR] = ACTIONS(81),
    [anon_sym_SLASH] = ACTIONS(83),
    [anon_sym_COLON] = ACTIONS(83),
    [anon_sym_PIPE] = ACTIONS(83),
    [anon_sym_PERCENT] = ACTIONS(81),
    [anon_sym_DOT] = ACTIONS(83),
    [anon_sym_AT] = ACTIONS(81),
    [anon_sym_DOLLAR] = ACTIONS(81),
    [anon_sym_AMP] = ACTIONS(81),
    [anon_sym_BQUOTE] = ACTIONS(81),
    [anon_sym_BANG] = ACTIONS(81),
    [sym_const_number] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(81),
    [anon_sym_CARET_] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(85),
    [anon_sym_LBRACK] = ACTIONS(85),
    [anon_sym_RBRACK] = ACTIONS(85),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_RBRACE] = ACTIONS(85),
    [anon_sym_LPAREN] = ACTIONS(85),
    [anon_sym_RPAREN] = ACTIONS(85),
    [sym_identifier] = ACTIONS(85),
    [sym_path] = ACTIONS(85),
    [anon_sym_EQ] = ACTIONS(87),
    [anon_sym_DOT_EQ] = ACTIONS(85),
    [anon_sym_COLON_EQ] = ACTIONS(85),
    [anon_sym_TILDE] = ACTIONS(85),
    [anon_sym_DASH_DASH] = ACTIONS(85),
    [anon_sym_GT_GT] = ACTIONS(85),
    [anon_sym_LT_LT] = ACTIONS(85),
    [anon_sym_PIPE_GT] = ACTIONS(85),
    [anon_sym_LT_PIPE] = ACTIONS(85),
    [anon_sym_COLON_COLON] = ACTIONS(85),
    [anon_sym_DOT_DOT] = ACTIONS(85),
    [anon_sym_GT_EQ] = ACTIONS(85),
    [anon_sym_LT_EQ] = ACTIONS(85),
    [anon_sym_EQ_EQ] = ACTIONS(85),
    [anon_sym_QMARK_GT] = ACTIONS(85),
    [anon_sym_LT_QMARK] = ACTIONS(87),
    [anon_sym_LT_QMARK_GT] = ACTIONS(85),
    [anon_sym_DASH_GT] = ACTIONS(85),
    [anon_sym_LT_DASH] = ACTIONS(87),
    [anon_sym_LT_DASH_GT] = ACTIONS(85),
    [anon_sym_PLUS] = ACTIONS(85),
    [anon_sym_DASH] = ACTIONS(87),
    [anon_sym_STAR] = ACTIONS(85),
    [anon_sym_SLASH] = ACTIONS(87),
    [anon_sym_COLON] = ACTIONS(87),
    [anon_sym_PIPE] = ACTIONS(87),
    [anon_sym_PERCENT] = ACTIONS(85),
    [anon_sym_DOT] = ACTIONS(87),
    [anon_sym_AT] = ACTIONS(85),
    [anon_sym_DOLLAR] = ACTIONS(85),
    [anon_sym_AMP] = ACTIONS(85),
    [anon_sym_BQUOTE] = ACTIONS(85),
    [anon_sym_BANG] = ACTIONS(85),
    [sym_const_number] = ACTIONS(85),
    [anon_sym_DQUOTE] = ACTIONS(85),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(85),
    [anon_sym_CARET_] = ACTIONS(85),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(89),
    [anon_sym_LBRACK] = ACTIONS(89),
    [anon_sym_RBRACK] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(89),
    [anon_sym_RPAREN] = ACTIONS(89),
    [sym_identifier] = ACTIONS(89),
    [sym_path] = ACTIONS(89),
    [anon_sym_EQ] = ACTIONS(91),
    [anon_sym_DOT_EQ] = ACTIONS(89),
    [anon_sym_COLON_EQ] = ACTIONS(89),
    [anon_sym_TILDE] = ACTIONS(89),
    [anon_sym_DASH_DASH] = ACTIONS(89),
    [anon_sym_GT_GT] = ACTIONS(31),
    [anon_sym_LT_LT] = ACTIONS(31),
    [anon_sym_PIPE_GT] = ACTIONS(31),
    [anon_sym_LT_PIPE] = ACTIONS(31),
    [anon_sym_COLON_COLON] = ACTIONS(31),
    [anon_sym_DOT_DOT] = ACTIONS(31),
    [anon_sym_GT_EQ] = ACTIONS(31),
    [anon_sym_LT_EQ] = ACTIONS(31),
    [anon_sym_EQ_EQ] = ACTIONS(31),
    [anon_sym_QMARK_GT] = ACTIONS(31),
    [anon_sym_LT_QMARK] = ACTIONS(33),
    [anon_sym_LT_QMARK_GT] = ACTIONS(31),
    [anon_sym_DASH_GT] = ACTIONS(31),
    [anon_sym_LT_DASH] = ACTIONS(33),
    [anon_sym_LT_DASH_GT] = ACTIONS(31),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(37),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(41),
    [anon_sym_COLON] = ACTIONS(43),
    [anon_sym_PIPE] = ACTIONS(43),
    [anon_sym_PERCENT] = ACTIONS(45),
    [anon_sym_DOT] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(89),
    [anon_sym_DOLLAR] = ACTIONS(89),
    [anon_sym_AMP] = ACTIONS(89),
    [anon_sym_BQUOTE] = ACTIONS(89),
    [anon_sym_BANG] = ACTIONS(89),
    [sym_const_number] = ACTIONS(89),
    [anon_sym_DQUOTE] = ACTIONS(89),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(89),
    [anon_sym_CARET_] = ACTIONS(89),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(89),
    [anon_sym_LBRACK] = ACTIONS(89),
    [anon_sym_RBRACK] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(89),
    [anon_sym_RPAREN] = ACTIONS(89),
    [sym_identifier] = ACTIONS(89),
    [sym_path] = ACTIONS(89),
    [anon_sym_EQ] = ACTIONS(91),
    [anon_sym_DOT_EQ] = ACTIONS(89),
    [anon_sym_COLON_EQ] = ACTIONS(89),
    [anon_sym_TILDE] = ACTIONS(89),
    [anon_sym_DASH_DASH] = ACTIONS(89),
    [anon_sym_GT_GT] = ACTIONS(89),
    [anon_sym_LT_LT] = ACTIONS(89),
    [anon_sym_PIPE_GT] = ACTIONS(89),
    [anon_sym_LT_PIPE] = ACTIONS(89),
    [anon_sym_COLON_COLON] = ACTIONS(89),
    [anon_sym_DOT_DOT] = ACTIONS(89),
    [anon_sym_GT_EQ] = ACTIONS(89),
    [anon_sym_LT_EQ] = ACTIONS(89),
    [anon_sym_EQ_EQ] = ACTIONS(89),
    [anon_sym_QMARK_GT] = ACTIONS(89),
    [anon_sym_LT_QMARK] = ACTIONS(91),
    [anon_sym_LT_QMARK_GT] = ACTIONS(89),
    [anon_sym_DASH_GT] = ACTIONS(89),
    [anon_sym_LT_DASH] = ACTIONS(91),
    [anon_sym_LT_DASH_GT] = ACTIONS(89),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(37),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(41),
    [anon_sym_COLON] = ACTIONS(43),
    [anon_sym_PIPE] = ACTIONS(43),
    [anon_sym_PERCENT] = ACTIONS(45),
    [anon_sym_DOT] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(89),
    [anon_sym_DOLLAR] = ACTIONS(89),
    [anon_sym_AMP] = ACTIONS(89),
    [anon_sym_BQUOTE] = ACTIONS(89),
    [anon_sym_BANG] = ACTIONS(89),
    [sym_const_number] = ACTIONS(89),
    [anon_sym_DQUOTE] = ACTIONS(89),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(89),
    [anon_sym_CARET_] = ACTIONS(89),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(89),
    [anon_sym_LBRACK] = ACTIONS(89),
    [anon_sym_RBRACK] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(89),
    [anon_sym_RPAREN] = ACTIONS(89),
    [sym_identifier] = ACTIONS(89),
    [sym_path] = ACTIONS(89),
    [anon_sym_EQ] = ACTIONS(91),
    [anon_sym_DOT_EQ] = ACTIONS(89),
    [anon_sym_COLON_EQ] = ACTIONS(89),
    [anon_sym_TILDE] = ACTIONS(89),
    [anon_sym_DASH_DASH] = ACTIONS(89),
    [anon_sym_GT_GT] = ACTIONS(89),
    [anon_sym_LT_LT] = ACTIONS(89),
    [anon_sym_PIPE_GT] = ACTIONS(89),
    [anon_sym_LT_PIPE] = ACTIONS(89),
    [anon_sym_COLON_COLON] = ACTIONS(89),
    [anon_sym_DOT_DOT] = ACTIONS(89),
    [anon_sym_GT_EQ] = ACTIONS(89),
    [anon_sym_LT_EQ] = ACTIONS(89),
    [anon_sym_EQ_EQ] = ACTIONS(89),
    [anon_sym_QMARK_GT] = ACTIONS(89),
    [anon_sym_LT_QMARK] = ACTIONS(91),
    [anon_sym_LT_QMARK_GT] = ACTIONS(89),
    [anon_sym_DASH_GT] = ACTIONS(89),
    [anon_sym_LT_DASH] = ACTIONS(91),
    [anon_sym_LT_DASH_GT] = ACTIONS(89),
    [anon_sym_PLUS] = ACTIONS(89),
    [anon_sym_DASH] = ACTIONS(91),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(41),
    [anon_sym_COLON] = ACTIONS(43),
    [anon_sym_PIPE] = ACTIONS(43),
    [anon_sym_PERCENT] = ACTIONS(45),
    [anon_sym_DOT] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(89),
    [anon_sym_DOLLAR] = ACTIONS(89),
    [anon_sym_AMP] = ACTIONS(89),
    [anon_sym_BQUOTE] = ACTIONS(89),
    [anon_sym_BANG] = ACTIONS(89),
    [sym_const_number] = ACTIONS(89),
    [anon_sym_DQUOTE] = ACTIONS(89),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(89),
    [anon_sym_CARET_] = ACTIONS(89),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(16)] = {
    [ts_builtin_sym_end] = ACTIONS(89),
    [anon_sym_LBRACK] = ACTIONS(89),
    [anon_sym_RBRACK] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(89),
    [anon_sym_RPAREN] = ACTIONS(89),
    [sym_identifier] = ACTIONS(89),
    [sym_path] = ACTIONS(89),
    [anon_sym_EQ] = ACTIONS(91),
    [anon_sym_DOT_EQ] = ACTIONS(89),
    [anon_sym_COLON_EQ] = ACTIONS(89),
    [anon_sym_TILDE] = ACTIONS(89),
    [anon_sym_DASH_DASH] = ACTIONS(89),
    [anon_sym_GT_GT] = ACTIONS(89),
    [anon_sym_LT_LT] = ACTIONS(89),
    [anon_sym_PIPE_GT] = ACTIONS(89),
    [anon_sym_LT_PIPE] = ACTIONS(89),
    [anon_sym_COLON_COLON] = ACTIONS(89),
    [anon_sym_DOT_DOT] = ACTIONS(89),
    [anon_sym_GT_EQ] = ACTIONS(89),
    [anon_sym_LT_EQ] = ACTIONS(89),
    [anon_sym_EQ_EQ] = ACTIONS(89),
    [anon_sym_QMARK_GT] = ACTIONS(89),
    [anon_sym_LT_QMARK] = ACTIONS(91),
    [anon_sym_LT_QMARK_GT] = ACTIONS(89),
    [anon_sym_DASH_GT] = ACTIONS(89),
    [anon_sym_LT_DASH] = ACTIONS(91),
    [anon_sym_LT_DASH_GT] = ACTIONS(89),
    [anon_sym_PLUS] = ACTIONS(89),
    [anon_sym_DASH] = ACTIONS(91),
    [anon_sym_STAR] = ACTIONS(89),
    [anon_sym_SLASH] = ACTIONS(91),
    [anon_sym_COLON] = ACTIONS(43),
    [anon_sym_PIPE] = ACTIONS(43),
    [anon_sym_PERCENT] = ACTIONS(45),
    [anon_sym_DOT] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(89),
    [anon_sym_DOLLAR] = ACTIONS(89),
    [anon_sym_AMP] = ACTIONS(89),
    [anon_sym_BQUOTE] = ACTIONS(89),
    [anon_sym_BANG] = ACTIONS(89),
    [sym_const_number] = ACTIONS(89),
    [anon_sym_DQUOTE] = ACTIONS(89),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(89),
    [anon_sym_CARET_] = ACTIONS(89),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(17)] = {
    [ts_builtin_sym_end] = ACTIONS(89),
    [anon_sym_LBRACK] = ACTIONS(89),
    [anon_sym_RBRACK] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(89),
    [anon_sym_RPAREN] = ACTIONS(89),
    [sym_identifier] = ACTIONS(89),
    [sym_path] = ACTIONS(89),
    [anon_sym_EQ] = ACTIONS(91),
    [anon_sym_DOT_EQ] = ACTIONS(89),
    [anon_sym_COLON_EQ] = ACTIONS(89),
    [anon_sym_TILDE] = ACTIONS(89),
    [anon_sym_DASH_DASH] = ACTIONS(89),
    [anon_sym_GT_GT] = ACTIONS(89),
    [anon_sym_LT_LT] = ACTIONS(89),
    [anon_sym_PIPE_GT] = ACTIONS(89),
    [anon_sym_LT_PIPE] = ACTIONS(89),
    [anon_sym_COLON_COLON] = ACTIONS(89),
    [anon_sym_DOT_DOT] = ACTIONS(89),
    [anon_sym_GT_EQ] = ACTIONS(89),
    [anon_sym_LT_EQ] = ACTIONS(89),
    [anon_sym_EQ_EQ] = ACTIONS(89),
    [anon_sym_QMARK_GT] = ACTIONS(89),
    [anon_sym_LT_QMARK] = ACTIONS(91),
    [anon_sym_LT_QMARK_GT] = ACTIONS(89),
    [anon_sym_DASH_GT] = ACTIONS(89),
    [anon_sym_LT_DASH] = ACTIONS(91),
    [anon_sym_LT_DASH_GT] = ACTIONS(89),
    [anon_sym_PLUS] = ACTIONS(89),
    [anon_sym_DASH] = ACTIONS(91),
    [anon_sym_STAR] = ACTIONS(89),
    [anon_sym_SLASH] = ACTIONS(91),
    [anon_sym_COLON] = ACTIONS(91),
    [anon_sym_PIPE] = ACTIONS(91),
    [anon_sym_PERCENT] = ACTIONS(89),
    [anon_sym_DOT] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(89),
    [anon_sym_DOLLAR] = ACTIONS(89),
    [anon_sym_AMP] = ACTIONS(89),
    [anon_sym_BQUOTE] = ACTIONS(89),
    [anon_sym_BANG] = ACTIONS(89),
    [sym_const_number] = ACTIONS(89),
    [anon_sym_DQUOTE] = ACTIONS(89),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(89),
    [anon_sym_CARET_] = ACTIONS(89),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(18)] = {
    [ts_builtin_sym_end] = ACTIONS(89),
    [anon_sym_LBRACK] = ACTIONS(89),
    [anon_sym_RBRACK] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(89),
    [anon_sym_RPAREN] = ACTIONS(89),
    [sym_identifier] = ACTIONS(89),
    [sym_path] = ACTIONS(89),
    [anon_sym_EQ] = ACTIONS(91),
    [anon_sym_DOT_EQ] = ACTIONS(89),
    [anon_sym_COLON_EQ] = ACTIONS(89),
    [anon_sym_TILDE] = ACTIONS(89),
    [anon_sym_DASH_DASH] = ACTIONS(89),
    [anon_sym_GT_GT] = ACTIONS(89),
    [anon_sym_LT_LT] = ACTIONS(89),
    [anon_sym_PIPE_GT] = ACTIONS(89),
    [anon_sym_LT_PIPE] = ACTIONS(89),
    [anon_sym_COLON_COLON] = ACTIONS(89),
    [anon_sym_DOT_DOT] = ACTIONS(89),
    [anon_sym_GT_EQ] = ACTIONS(89),
    [anon_sym_LT_EQ] = ACTIONS(89),
    [anon_sym_EQ_EQ] = ACTIONS(89),
    [anon_sym_QMARK_GT] = ACTIONS(89),
    [anon_sym_LT_QMARK] = ACTIONS(91),
    [anon_sym_LT_QMARK_GT] = ACTIONS(89),
    [anon_sym_DASH_GT] = ACTIONS(89),
    [anon_sym_LT_DASH] = ACTIONS(91),
    [anon_sym_LT_DASH_GT] = ACTIONS(89),
    [anon_sym_PLUS] = ACTIONS(89),
    [anon_sym_DASH] = ACTIONS(91),
    [anon_sym_STAR] = ACTIONS(89),
    [anon_sym_SLASH] = ACTIONS(91),
    [anon_sym_COLON] = ACTIONS(91),
    [anon_sym_PIPE] = ACTIONS(91),
    [anon_sym_PERCENT] = ACTIONS(89),
    [anon_sym_DOT] = ACTIONS(91),
    [anon_sym_AT] = ACTIONS(89),
    [anon_sym_DOLLAR] = ACTIONS(89),
    [anon_sym_AMP] = ACTIONS(89),
    [anon_sym_BQUOTE] = ACTIONS(89),
    [anon_sym_BANG] = ACTIONS(89),
    [sym_const_number] = ACTIONS(89),
    [anon_sym_DQUOTE] = ACTIONS(89),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(89),
    [anon_sym_CARET_] = ACTIONS(89),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(19)] = {
    [ts_builtin_sym_end] = ACTIONS(93),
    [anon_sym_LBRACK] = ACTIONS(93),
    [anon_sym_RBRACK] = ACTIONS(93),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_RBRACE] = ACTIONS(93),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_RPAREN] = ACTIONS(93),
    [sym_identifier] = ACTIONS(93),
    [sym_path] = ACTIONS(93),
    [anon_sym_EQ] = ACTIONS(95),
    [anon_sym_DOT_EQ] = ACTIONS(93),
    [anon_sym_COLON_EQ] = ACTIONS(93),
    [anon_sym_TILDE] = ACTIONS(93),
    [anon_sym_DASH_DASH] = ACTIONS(93),
    [anon_sym_GT_GT] = ACTIONS(93),
    [anon_sym_LT_LT] = ACTIONS(93),
    [anon_sym_PIPE_GT] = ACTIONS(93),
    [anon_sym_LT_PIPE] = ACTIONS(93),
    [anon_sym_COLON_COLON] = ACTIONS(93),
    [anon_sym_DOT_DOT] = ACTIONS(93),
    [anon_sym_GT_EQ] = ACTIONS(93),
    [anon_sym_LT_EQ] = ACTIONS(93),
    [anon_sym_EQ_EQ] = ACTIONS(93),
    [anon_sym_QMARK_GT] = ACTIONS(93),
    [anon_sym_LT_QMARK] = ACTIONS(95),
    [anon_sym_LT_QMARK_GT] = ACTIONS(93),
    [anon_sym_DASH_GT] = ACTIONS(93),
    [anon_sym_LT_DASH] = ACTIONS(95),
    [anon_sym_LT_DASH_GT] = ACTIONS(93),
    [anon_sym_PLUS] = ACTIONS(93),
    [anon_sym_DASH] = ACTIONS(95),
    [anon_sym_STAR] = ACTIONS(93),
    [anon_sym_SLASH] = ACTIONS(95),
    [anon_sym_COLON] = ACTIONS(95),
    [anon_sym_PIPE] = ACTIONS(95),
    [anon_sym_PERCENT] = ACTIONS(93),
    [anon_sym_DOT] = ACTIONS(95),
    [anon_sym_AT] = ACTIONS(93),
    [anon_sym_DOLLAR] = ACTIONS(93),
    [anon_sym_AMP] = ACTIONS(93),
    [anon_sym_BQUOTE] = ACTIONS(93),
    [anon_sym_BANG] = ACTIONS(93),
    [sym_const_number] = ACTIONS(93),
    [anon_sym_DQUOTE] = ACTIONS(93),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(93),
    [anon_sym_CARET_] = ACTIONS(93),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(20)] = {
    [ts_builtin_sym_end] = ACTIONS(97),
    [anon_sym_LBRACK] = ACTIONS(97),
    [anon_sym_RBRACK] = ACTIONS(97),
    [anon_sym_LBRACE] = ACTIONS(97),
    [anon_sym_RBRACE] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(97),
    [anon_sym_RPAREN] = ACTIONS(97),
    [sym_identifier] = ACTIONS(97),
    [sym_path] = ACTIONS(97),
    [anon_sym_EQ] = ACTIONS(99),
    [anon_sym_DOT_EQ] = ACTIONS(97),
    [anon_sym_COLON_EQ] = ACTIONS(97),
    [anon_sym_TILDE] = ACTIONS(97),
    [anon_sym_DASH_DASH] = ACTIONS(97),
    [anon_sym_GT_GT] = ACTIONS(97),
    [anon_sym_LT_LT] = ACTIONS(97),
    [anon_sym_PIPE_GT] = ACTIONS(97),
    [anon_sym_LT_PIPE] = ACTIONS(97),
    [anon_sym_COLON_COLON] = ACTIONS(97),
    [anon_sym_DOT_DOT] = ACTIONS(97),
    [anon_sym_GT_EQ] = ACTIONS(97),
    [anon_sym_LT_EQ] = ACTIONS(97),
    [anon_sym_EQ_EQ] = ACTIONS(97),
    [anon_sym_QMARK_GT] = ACTIONS(97),
    [anon_sym_LT_QMARK] = ACTIONS(99),
    [anon_sym_LT_QMARK_GT] = ACTIONS(97),
    [anon_sym_DASH_GT] = ACTIONS(97),
    [anon_sym_LT_DASH] = ACTIONS(99),
    [anon_sym_LT_DASH_GT] = ACTIONS(97),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_DASH] = ACTIONS(99),
    [anon_sym_STAR] = ACTIONS(97),
    [anon_sym_SLASH] = ACTIONS(99),
    [anon_sym_COLON] = ACTIONS(99),
    [anon_sym_PIPE] = ACTIONS(99),
    [anon_sym_PERCENT] = ACTIONS(97),
    [anon_sym_DOT] = ACTIONS(99),
    [anon_sym_AT] = ACTIONS(97),
    [anon_sym_DOLLAR] = ACTIONS(97),
    [anon_sym_AMP] = ACTIONS(97),
    [anon_sym_BQUOTE] = ACTIONS(97),
    [anon_sym_BANG] = ACTIONS(97),
    [sym_const_number] = ACTIONS(97),
    [anon_sym_DQUOTE] = ACTIONS(97),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(97),
    [anon_sym_CARET_] = ACTIONS(97),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(21)] = {
    [ts_builtin_sym_end] = ACTIONS(101),
    [anon_sym_LBRACK] = ACTIONS(101),
    [anon_sym_RBRACK] = ACTIONS(101),
    [anon_sym_LBRACE] = ACTIONS(101),
    [anon_sym_RBRACE] = ACTIONS(101),
    [anon_sym_LPAREN] = ACTIONS(101),
    [anon_sym_RPAREN] = ACTIONS(101),
    [sym_identifier] = ACTIONS(101),
    [sym_path] = ACTIONS(101),
    [anon_sym_EQ] = ACTIONS(103),
    [anon_sym_DOT_EQ] = ACTIONS(101),
    [anon_sym_COLON_EQ] = ACTIONS(101),
    [anon_sym_TILDE] = ACTIONS(101),
    [anon_sym_DASH_DASH] = ACTIONS(101),
    [anon_sym_GT_GT] = ACTIONS(101),
    [anon_sym_LT_LT] = ACTIONS(101),
    [anon_sym_PIPE_GT] = ACTIONS(101),
    [anon_sym_LT_PIPE] = ACTIONS(101),
    [anon_sym_COLON_COLON] = ACTIONS(101),
    [anon_sym_DOT_DOT] = ACTIONS(101),
    [anon_sym_GT_EQ] = ACTIONS(101),
    [anon_sym_LT_EQ] = ACTIONS(101),
    [anon_sym_EQ_EQ] = ACTIONS(101),
    [anon_sym_QMARK_GT] = ACTIONS(101),
    [anon_sym_LT_QMARK] = ACTIONS(103),
    [anon_sym_LT_QMARK_GT] = ACTIONS(101),
    [anon_sym_DASH_GT] = ACTIONS(101),
    [anon_sym_LT_DASH] = ACTIONS(103),
    [anon_sym_LT_DASH_GT] = ACTIONS(101),
    [anon_sym_PLUS] = ACTIONS(101),
    [anon_sym_DASH] = ACTIONS(103),
    [anon_sym_STAR] = ACTIONS(101),
    [anon_sym_SLASH] = ACTIONS(103),
    [anon_sym_COLON] = ACTIONS(103),
    [anon_sym_PIPE] = ACTIONS(103),
    [anon_sym_PERCENT] = ACTIONS(101),
    [anon_sym_DOT] = ACTIONS(103),
    [anon_sym_AT] = ACTIONS(101),
    [anon_sym_DOLLAR] = ACTIONS(101),
    [anon_sym_AMP] = ACTIONS(101),
    [anon_sym_BQUOTE] = ACTIONS(101),
    [anon_sym_BANG] = ACTIONS(101),
    [sym_const_number] = ACTIONS(101),
    [anon_sym_DQUOTE] = ACTIONS(101),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(101),
    [anon_sym_CARET_] = ACTIONS(101),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(22)] = {
    [ts_builtin_sym_end] = ACTIONS(105),
    [anon_sym_LBRACK] = ACTIONS(105),
    [anon_sym_RBRACK] = ACTIONS(105),
    [anon_sym_LBRACE] = ACTIONS(105),
    [anon_sym_RBRACE] = ACTIONS(105),
    [anon_sym_LPAREN] = ACTIONS(105),
    [anon_sym_RPAREN] = ACTIONS(105),
    [sym_identifier] = ACTIONS(105),
    [sym_path] = ACTIONS(105),
    [anon_sym_EQ] = ACTIONS(107),
    [anon_sym_DOT_EQ] = ACTIONS(105),
    [anon_sym_COLON_EQ] = ACTIONS(105),
    [anon_sym_TILDE] = ACTIONS(105),
    [anon_sym_DASH_DASH] = ACTIONS(105),
    [anon_sym_GT_GT] = ACTIONS(105),
    [anon_sym_LT_LT] = ACTIONS(105),
    [anon_sym_PIPE_GT] = ACTIONS(105),
    [anon_sym_LT_PIPE] = ACTIONS(105),
    [anon_sym_COLON_COLON] = ACTIONS(105),
    [anon_sym_DOT_DOT] = ACTIONS(105),
    [anon_sym_GT_EQ] = ACTIONS(105),
    [anon_sym_LT_EQ] = ACTIONS(105),
    [anon_sym_EQ_EQ] = ACTIONS(105),
    [anon_sym_QMARK_GT] = ACTIONS(105),
    [anon_sym_LT_QMARK] = ACTIONS(107),
    [anon_sym_LT_QMARK_GT] = ACTIONS(105),
    [anon_sym_DASH_GT] = ACTIONS(105),
    [anon_sym_LT_DASH] = ACTIONS(107),
    [anon_sym_LT_DASH_GT] = ACTIONS(105),
    [anon_sym_PLUS] = ACTIONS(105),
    [anon_sym_DASH] = ACTIONS(107),
    [anon_sym_STAR] = ACTIONS(105),
    [anon_sym_SLASH] = ACTIONS(107),
    [anon_sym_COLON] = ACTIONS(107),
    [anon_sym_PIPE] = ACTIONS(107),
    [anon_sym_PERCENT] = ACTIONS(105),
    [anon_sym_DOT] = ACTIONS(107),
    [anon_sym_AT] = ACTIONS(105),
    [anon_sym_DOLLAR] = ACTIONS(105),
    [anon_sym_AMP] = ACTIONS(105),
    [anon_sym_BQUOTE] = ACTIONS(105),
    [anon_sym_BANG] = ACTIONS(105),
    [sym_const_number] = ACTIONS(105),
    [anon_sym_DQUOTE] = ACTIONS(105),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(105),
    [anon_sym_CARET_] = ACTIONS(105),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(23)] = {
    [ts_builtin_sym_end] = ACTIONS(109),
    [anon_sym_LBRACK] = ACTIONS(109),
    [anon_sym_RBRACK] = ACTIONS(109),
    [anon_sym_LBRACE] = ACTIONS(109),
    [anon_sym_RBRACE] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(109),
    [anon_sym_RPAREN] = ACTIONS(109),
    [sym_identifier] = ACTIONS(109),
    [sym_path] = ACTIONS(109),
    [anon_sym_EQ] = ACTIONS(111),
    [anon_sym_DOT_EQ] = ACTIONS(109),
    [anon_sym_COLON_EQ] = ACTIONS(109),
    [anon_sym_TILDE] = ACTIONS(109),
    [anon_sym_DASH_DASH] = ACTIONS(109),
    [anon_sym_GT_GT] = ACTIONS(109),
    [anon_sym_LT_LT] = ACTIONS(109),
    [anon_sym_PIPE_GT] = ACTIONS(109),
    [anon_sym_LT_PIPE] = ACTIONS(109),
    [anon_sym_COLON_COLON] = ACTIONS(109),
    [anon_sym_DOT_DOT] = ACTIONS(109),
    [anon_sym_GT_EQ] = ACTIONS(109),
    [anon_sym_LT_EQ] = ACTIONS(109),
    [anon_sym_EQ_EQ] = ACTIONS(109),
    [anon_sym_QMARK_GT] = ACTIONS(109),
    [anon_sym_LT_QMARK] = ACTIONS(111),
    [anon_sym_LT_QMARK_GT] = ACTIONS(109),
    [anon_sym_DASH_GT] = ACTIONS(109),
    [anon_sym_LT_DASH] = ACTIONS(111),
    [anon_sym_LT_DASH_GT] = ACTIONS(109),
    [anon_sym_PLUS] = ACTIONS(109),
    [anon_sym_DASH] = ACTIONS(111),
    [anon_sym_STAR] = ACTIONS(109),
    [anon_sym_SLASH] = ACTIONS(111),
    [anon_sym_COLON] = ACTIONS(111),
    [anon_sym_PIPE] = ACTIONS(111),
    [anon_sym_PERCENT] = ACTIONS(109),
    [anon_sym_DOT] = ACTIONS(111),
    [anon_sym_AT] = ACTIONS(109),
    [anon_sym_DOLLAR] = ACTIONS(109),
    [anon_sym_AMP] = ACTIONS(109),
    [anon_sym_BQUOTE] = ACTIONS(109),
    [anon_sym_BANG] = ACTIONS(109),
    [sym_const_number] = ACTIONS(109),
    [anon_sym_DQUOTE] = ACTIONS(109),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(109),
    [anon_sym_CARET_] = ACTIONS(109),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(24)] = {
    [ts_builtin_sym_end] = ACTIONS(113),
    [anon_sym_LBRACK] = ACTIONS(113),
    [anon_sym_RBRACK] = ACTIONS(113),
    [anon_sym_LBRACE] = ACTIONS(113),
    [anon_sym_RBRACE] = ACTIONS(113),
    [anon_sym_LPAREN] = ACTIONS(113),
    [anon_sym_RPAREN] = ACTIONS(113),
    [sym_identifier] = ACTIONS(113),
    [sym_path] = ACTIONS(113),
    [anon_sym_EQ] = ACTIONS(115),
    [anon_sym_DOT_EQ] = ACTIONS(113),
    [anon_sym_COLON_EQ] = ACTIONS(113),
    [anon_sym_TILDE] = ACTIONS(113),
    [anon_sym_DASH_DASH] = ACTIONS(113),
    [anon_sym_GT_GT] = ACTIONS(113),
    [anon_sym_LT_LT] = ACTIONS(113),
    [anon_sym_PIPE_GT] = ACTIONS(113),
    [anon_sym_LT_PIPE] = ACTIONS(113),
    [anon_sym_COLON_COLON] = ACTIONS(113),
    [anon_sym_DOT_DOT] = ACTIONS(113),
    [anon_sym_GT_EQ] = ACTIONS(113),
    [anon_sym_LT_EQ] = ACTIONS(113),
    [anon_sym_EQ_EQ] = ACTIONS(113),
    [anon_sym_QMARK_GT] = ACTIONS(113),
    [anon_sym_LT_QMARK] = ACTIONS(115),
    [anon_sym_LT_QMARK_GT] = ACTIONS(113),
    [anon_sym_DASH_GT] = ACTIONS(113),
    [anon_sym_LT_DASH] = ACTIONS(115),
    [anon_sym_LT_DASH_GT] = ACTIONS(113),
    [anon_sym_PLUS] = ACTIONS(113),
    [anon_sym_DASH] = ACTIONS(115),
    [anon_sym_STAR] = ACTIONS(113),
    [anon_sym_SLASH] = ACTIONS(115),
    [anon_sym_COLON] = ACTIONS(115),
    [anon_sym_PIPE] = ACTIONS(115),
    [anon_sym_PERCENT] = ACTIONS(113),
    [anon_sym_DOT] = ACTIONS(115),
    [anon_sym_AT] = ACTIONS(113),
    [anon_sym_DOLLAR] = ACTIONS(113),
    [anon_sym_AMP] = ACTIONS(113),
    [anon_sym_BQUOTE] = ACTIONS(113),
    [anon_sym_BANG] = ACTIONS(113),
    [sym_const_number] = ACTIONS(113),
    [anon_sym_DQUOTE] = ACTIONS(113),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(113),
    [anon_sym_CARET_] = ACTIONS(113),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      sym_pair,
    ACTIONS(13), 2,
      sym_identifier,
      sym_path,
    STATE(5), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_BANG,
    STATE(2), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [55] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(119), 1,
      anon_sym_RBRACK,
    STATE(53), 1,
      sym_pair,
    ACTIONS(13), 2,
      sym_identifier,
      sym_path,
    STATE(5), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_BANG,
    STATE(2), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [110] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      sym_pair,
    ACTIONS(13), 2,
      sym_identifier,
      sym_path,
    STATE(5), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_BANG,
    STATE(2), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [165] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(123), 2,
      sym_identifier,
      sym_path,
    STATE(5), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_BANG,
    STATE(9), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [214] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(125), 2,
      sym_identifier,
      sym_path,
    STATE(5), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_BANG,
    STATE(13), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [263] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(127), 2,
      sym_identifier,
      sym_path,
    STATE(5), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_BANG,
    STATE(14), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [312] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(129), 2,
      sym_identifier,
      sym_path,
    STATE(5), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_BANG,
    STATE(18), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [361] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(131), 2,
      sym_identifier,
      sym_path,
    STATE(5), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_BANG,
    STATE(15), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [410] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(133), 2,
      sym_identifier,
      sym_path,
    STATE(5), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_BANG,
    STATE(16), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [459] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(135), 2,
      sym_identifier,
      sym_path,
    STATE(5), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_BANG,
    STATE(17), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [508] = 5,
    ACTIONS(137), 1,
      aux_sym_cat_string_token2,
    ACTIONS(139), 1,
      anon_sym__,
    ACTIONS(141), 1,
      anon_sym__CARET,
    ACTIONS(143), 1,
      sym_comment,
    STATE(38), 1,
      aux_sym_cat_string_repeat1,
  [524] = 5,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_LF_COMMA_COMMA_COMMA,
    ACTIONS(147), 1,
      sym_paragrapth_head,
    ACTIONS(149), 1,
      sym_paragrapth_content,
    STATE(42), 1,
      aux_sym_paragrapth_repeat1,
  [540] = 5,
    ACTIONS(139), 1,
      anon_sym__,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(151), 1,
      aux_sym_cat_string_token2,
    ACTIONS(153), 1,
      anon_sym__CARET,
    STATE(40), 1,
      aux_sym_cat_string_repeat1,
  [556] = 5,
    ACTIONS(139), 1,
      anon_sym__,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(151), 1,
      aux_sym_cat_string_token2,
    ACTIONS(155), 1,
      anon_sym__CARET,
    STATE(40), 1,
      aux_sym_cat_string_repeat1,
  [572] = 5,
    ACTIONS(139), 1,
      anon_sym__,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym__CARET,
    ACTIONS(157), 1,
      aux_sym_cat_string_token2,
    STATE(37), 1,
      aux_sym_cat_string_repeat1,
  [588] = 5,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(159), 1,
      aux_sym_cat_string_token2,
    ACTIONS(162), 1,
      anon_sym__,
    ACTIONS(165), 1,
      anon_sym__CARET,
    STATE(40), 1,
      aux_sym_cat_string_repeat1,
  [604] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
  [614] = 4,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_LF_COMMA_COMMA_COMMA,
    ACTIONS(171), 1,
      sym_paragrapth_content,
    STATE(43), 1,
      aux_sym_paragrapth_repeat1,
  [627] = 4,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_LF_COMMA_COMMA_COMMA,
    ACTIONS(175), 1,
      sym_paragrapth_content,
    STATE(43), 1,
      aux_sym_paragrapth_repeat1,
  [640] = 4,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(171), 1,
      sym_paragrapth_content,
    ACTIONS(178), 1,
      anon_sym_LF_COMMA_COMMA_COMMA,
    STATE(43), 1,
      aux_sym_paragrapth_repeat1,
  [653] = 4,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_LF_COMMA_COMMA_COMMA,
    ACTIONS(182), 1,
      sym_paragrapth_content,
    STATE(44), 1,
      aux_sym_paragrapth_repeat1,
  [666] = 2,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(165), 3,
      aux_sym_cat_string_token2,
      anon_sym__,
      anon_sym__CARET,
  [675] = 3,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(184), 1,
      sym_paragrapth_head,
    ACTIONS(186), 1,
      aux_sym_cat_string_token1,
  [685] = 2,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_LF,
  [692] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_DQUOTE,
  [699] = 2,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(192), 1,
      aux_sym_cat_string_token1,
  [706] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      ts_builtin_sym_end,
  [713] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
  [720] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_RBRACK,
  [727] = 2,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(200), 1,
      aux_sym_const_string_token1,
  [734] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
  [741] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
  [748] = 2,
    ACTIONS(143), 1,
      sym_comment,
    ACTIONS(206), 1,
      aux_sym_cat_string_token3,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(25)] = 0,
  [SMALL_STATE(26)] = 55,
  [SMALL_STATE(27)] = 110,
  [SMALL_STATE(28)] = 165,
  [SMALL_STATE(29)] = 214,
  [SMALL_STATE(30)] = 263,
  [SMALL_STATE(31)] = 312,
  [SMALL_STATE(32)] = 361,
  [SMALL_STATE(33)] = 410,
  [SMALL_STATE(34)] = 459,
  [SMALL_STATE(35)] = 508,
  [SMALL_STATE(36)] = 524,
  [SMALL_STATE(37)] = 540,
  [SMALL_STATE(38)] = 556,
  [SMALL_STATE(39)] = 572,
  [SMALL_STATE(40)] = 588,
  [SMALL_STATE(41)] = 604,
  [SMALL_STATE(42)] = 614,
  [SMALL_STATE(43)] = 627,
  [SMALL_STATE(44)] = 640,
  [SMALL_STATE(45)] = 653,
  [SMALL_STATE(46)] = 666,
  [SMALL_STATE(47)] = 675,
  [SMALL_STATE(48)] = 685,
  [SMALL_STATE(49)] = 692,
  [SMALL_STATE(50)] = 699,
  [SMALL_STATE(51)] = 706,
  [SMALL_STATE(52)] = 713,
  [SMALL_STATE(53)] = 720,
  [SMALL_STATE(54)] = 727,
  [SMALL_STATE(55)] = 734,
  [SMALL_STATE(56)] = 741,
  [SMALL_STATE(57)] = 748,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragrapth, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragrapth, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_string, 5, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cat_string, 5, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_value, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_value, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_curly_list, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_curly_list, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_curly_list, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_curly_list, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_string, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_string, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragrapth, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragrapth, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_string, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cat_string, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragrapth, 4, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragrapth, 4, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_string, 4, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cat_string, 4, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragrapth, 5, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragrapth, 5, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [159] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cat_string_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [162] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cat_string_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cat_string_repeat1, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_paragrapth_repeat1, 2, 0, 0),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragrapth_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_chimera(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
