/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 58
#define LARGE_STATE_COUNT 25
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 46
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_RBRACK = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  sym_identifier = 7,
  sym_path = 8,
  anon_sym_EQ = 9,
  anon_sym_GT_GT = 10,
  anon_sym_LT_LT = 11,
  anon_sym_PIPE_GT = 12,
  anon_sym_LT_PIPE = 13,
  anon_sym_COLON_COLON = 14,
  anon_sym_DOT_DOT = 15,
  anon_sym_GT_EQ = 16,
  anon_sym_LT_EQ = 17,
  anon_sym_EQ_EQ = 18,
  anon_sym_PLUS = 19,
  anon_sym_DASH = 20,
  anon_sym_STAR = 21,
  anon_sym_SLASH = 22,
  anon_sym_COLON = 23,
  anon_sym_PIPE = 24,
  anon_sym_DOT = 25,
  anon_sym_AT = 26,
  anon_sym_DOLLAR = 27,
  anon_sym_AMP = 28,
  anon_sym_BQUOTE = 29,
  anon_sym_PERCENT = 30,
  sym_const_number = 31,
  anon_sym_DQUOTE = 32,
  aux_sym_const_string_token1 = 33,
  anon_sym_COMMA_COMMA_COMMA = 34,
  anon_sym_LF = 35,
  anon_sym_LF_COMMA_COMMA_COMMA = 36,
  sym_paragrapth_head = 37,
  sym_paragrapth_content = 38,
  anon_sym_CARET_ = 39,
  aux_sym_cat_string_token1 = 40,
  aux_sym_cat_string_token2 = 41,
  anon_sym__ = 42,
  aux_sym_cat_string_token3 = 43,
  anon_sym__CARET = 44,
  sym_comment = 45,
  sym_source_file = 46,
  sym_list = 47,
  sym_curly_list = 48,
  sym_group = 49,
  sym_binary_expression = 50,
  sym_unary_expression = 51,
  sym_const_value = 52,
  sym_const_string = 53,
  sym_paragrapth = 54,
  sym_cat_string = 55,
  aux_sym_source_file_repeat1 = 56,
  aux_sym_paragrapth_repeat1 = 57,
  aux_sym_cat_string_repeat1 = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_identifier] = "identifier",
  [sym_path] = "path",
  [anon_sym_EQ] = "=",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_PIPE_GT] = "|>",
  [anon_sym_LT_PIPE] = "<|",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "|",
  [anon_sym_DOT] = ".",
  [anon_sym_AT] = "@",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_AMP] = "&",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_PERCENT] = "%",
  [sym_const_number] = "const_number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_const_string_token1] = "const_string_token1",
  [anon_sym_COMMA_COMMA_COMMA] = ",,,",
  [anon_sym_LF] = "\n",
  [anon_sym_LF_COMMA_COMMA_COMMA] = "\n,,,",
  [sym_paragrapth_head] = "paragrapth_head",
  [sym_paragrapth_content] = "paragrapth_content",
  [anon_sym_CARET_] = "^_",
  [aux_sym_cat_string_token1] = "cat_string_token1",
  [aux_sym_cat_string_token2] = "cat_string_token2",
  [anon_sym__] = "_",
  [aux_sym_cat_string_token3] = "cat_string_token3",
  [anon_sym__CARET] = "_^",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_list] = "list",
  [sym_curly_list] = "curly_list",
  [sym_group] = "group",
  [sym_binary_expression] = "binary_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_const_value] = "const_value",
  [sym_const_string] = "const_string",
  [sym_paragrapth] = "paragrapth",
  [sym_cat_string] = "cat_string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_paragrapth_repeat1] = "paragrapth_repeat1",
  [aux_sym_cat_string_repeat1] = "cat_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_identifier] = sym_identifier,
  [sym_path] = sym_path,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_PIPE_GT] = anon_sym_PIPE_GT,
  [anon_sym_LT_PIPE] = anon_sym_LT_PIPE,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_const_number] = sym_const_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_const_string_token1] = aux_sym_const_string_token1,
  [anon_sym_COMMA_COMMA_COMMA] = anon_sym_COMMA_COMMA_COMMA,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LF_COMMA_COMMA_COMMA] = anon_sym_LF_COMMA_COMMA_COMMA,
  [sym_paragrapth_head] = sym_paragrapth_head,
  [sym_paragrapth_content] = sym_paragrapth_content,
  [anon_sym_CARET_] = anon_sym_CARET_,
  [aux_sym_cat_string_token1] = aux_sym_cat_string_token1,
  [aux_sym_cat_string_token2] = aux_sym_cat_string_token2,
  [anon_sym__] = anon_sym__,
  [aux_sym_cat_string_token3] = aux_sym_cat_string_token3,
  [anon_sym__CARET] = anon_sym__CARET,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_list] = sym_list,
  [sym_curly_list] = sym_curly_list,
  [sym_group] = sym_group,
  [sym_binary_expression] = sym_binary_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_const_value] = sym_const_value,
  [sym_const_string] = sym_const_string,
  [sym_paragrapth] = sym_paragrapth,
  [sym_cat_string] = sym_cat_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_paragrapth_repeat1] = aux_sym_paragrapth_repeat1,
  [aux_sym_cat_string_repeat1] = aux_sym_cat_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_const_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_const_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA_COMMA_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF_COMMA_COMMA_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_paragrapth_head] = {
    .visible = true,
    .named = true,
  },
  [sym_paragrapth_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_CARET_] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_cat_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cat_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_cat_string_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym__CARET] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_curly_list] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_const_value] = {
    .visible = true,
    .named = true,
  },
  [sym_const_string] = {
    .visible = true,
    .named = true,
  },
  [sym_paragrapth] = {
    .visible = true,
    .named = true,
  },
  [sym_cat_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragrapth_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cat_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
};

const TSCharacterRange sym_path_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '('}, {'*', '+'}, {'-', ':'}, {'<', '\\'}, {'^', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '\n', 1,
        '"', 47,
        '$', 42,
        '%', 45,
        '&', 43,
        '(', 20,
        ')', 21,
        '*', 36,
        '+', 34,
        ',', 6,
        '-', 35,
        '.', 40,
        '/', 37,
        ':', 38,
        ';', 73,
        '<', 10,
        '=', 24,
        '>', 11,
        '@', 41,
        '[', 16,
        ']', 17,
        '^', 12,
        '_', 68,
        '`', 44,
        '{', 18,
        '|', 39,
        '}', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 1,
        '"', 47,
        '$', 42,
        '%', 45,
        '&', 43,
        '(', 20,
        ')', 21,
        '*', 36,
        '+', 34,
        ',', 6,
        '-', 35,
        '.', 40,
        '/', 37,
        ':', 38,
        ';', 73,
        '<', 10,
        '=', 24,
        '>', 11,
        '@', 41,
        '[', 16,
        ']', 17,
        '^', 12,
        '_', 68,
        '`', 44,
        '{', 18,
        '|', 39,
        '}', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == ';') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(57);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(58);
      if (lookahead == ';') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(59);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == ';') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == ',') ADVANCE(51);
      END_STATE();
    case 6:
      if (lookahead == ',') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == ';') ADVANCE(73);
      if (lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) SKIP(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 8:
      if (lookahead == ';') ADVANCE(67);
      if (lookahead == '_') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(66);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 9:
      if (lookahead == ';') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '^') ADVANCE(69);
      END_STATE();
    case 10:
      if (lookahead == '<') ADVANCE(26);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '|') ADVANCE(28);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == '_') ADVANCE(63);
      END_STATE();
    case 13:
      if ((!eof && set_contains(sym_path_character_set_1, 9, lookahead))) ADVANCE(23);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 47,
        '$', 42,
        '%', 45,
        '&', 43,
        '(', 20,
        ')', 21,
        '*', 36,
        '+', 34,
        ',', 6,
        '-', 35,
        '.', 40,
        '/', 37,
        ':', 38,
        ';', 73,
        '<', 10,
        '=', 24,
        '>', 11,
        '@', 41,
        '[', 16,
        ']', 17,
        '^', 12,
        '`', 44,
        '{', 18,
        '|', 39,
        '}', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) SKIP(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_path);
      if (lookahead == '/') ADVANCE(23);
      if ((!eof && set_contains(sym_path_character_set_1, 9, lookahead))) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PIPE_GT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT_PIPE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if ((!eof && set_contains(sym_path_character_set_1, 9, lookahead))) ADVANCE(23);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(29);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '>') ADVANCE(27);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_const_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_const_string_token1);
      if (lookahead == '\n') ADVANCE(50);
      if (lookahead == '"') ADVANCE(73);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_const_string_token1);
      if (lookahead == ';') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(50);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_const_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COMMA_COMMA_COMMA);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LF_COMMA_COMMA_COMMA);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_paragrapth_head);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_paragrapth_head);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_paragrapth_content);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == ',') ADVANCE(61);
      if (lookahead == ';') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(57);
      if (('+' <= lookahead && lookahead <= '-') ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_paragrapth_content);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == ';') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(57);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_paragrapth_content);
      if (lookahead == '\n') ADVANCE(58);
      if (lookahead == ',') ADVANCE(61);
      if (lookahead == ';') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(59);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_paragrapth_content);
      if (lookahead == '\n') ADVANCE(58);
      if (lookahead == ';') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(59);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_paragrapth_content);
      if (lookahead == ',') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_paragrapth_content);
      if (lookahead == ',') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_paragrapth_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_CARET_);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_cat_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_cat_string_token2);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_cat_string_token2);
      if (lookahead == ';') ADVANCE(67);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '_') ADVANCE(65);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_cat_string_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym__);
      if (lookahead == '^') ADVANCE(72);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_cat_string_token3);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_cat_string_token3);
      if (lookahead == ';') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '^') ADVANCE(69);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_cat_string_token3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym__CARET);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 14},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 14},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 14},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 14},
  [17] = {.lex_state = 14},
  [18] = {.lex_state = 14},
  [19] = {.lex_state = 14},
  [20] = {.lex_state = 14},
  [21] = {.lex_state = 14},
  [22] = {.lex_state = 14},
  [23] = {.lex_state = 14},
  [24] = {.lex_state = 14},
  [25] = {.lex_state = 14},
  [26] = {.lex_state = 14},
  [27] = {.lex_state = 14},
  [28] = {.lex_state = 14},
  [29] = {.lex_state = 14},
  [30] = {.lex_state = 14},
  [31] = {.lex_state = 14},
  [32] = {.lex_state = 14},
  [33] = {.lex_state = 14},
  [34] = {.lex_state = 14},
  [35] = {.lex_state = 14},
  [36] = {.lex_state = 14},
  [37] = {.lex_state = 14},
  [38] = {.lex_state = 14},
  [39] = {.lex_state = 14},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 8},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 49},
  [55] = {.lex_state = 9},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_path] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_PIPE_GT] = ACTIONS(1),
    [anon_sym_LT_PIPE] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [sym_const_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(1),
    [anon_sym_LF_COMMA_COMMA_COMMA] = ACTIONS(1),
    [anon_sym_CARET_] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym__CARET] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(56),
    [sym_list] = STATE(3),
    [sym_curly_list] = STATE(3),
    [sym_group] = STATE(3),
    [sym_binary_expression] = STATE(3),
    [sym_unary_expression] = STATE(3),
    [sym_const_value] = STATE(3),
    [sym_const_string] = STATE(4),
    [sym_paragrapth] = STATE(4),
    [sym_cat_string] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(31),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [sym_path] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_DOLLAR] = ACTIONS(15),
    [anon_sym_AMP] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(15),
    [sym_const_number] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(21),
    [anon_sym_CARET_] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(25),
    [sym_identifier] = ACTIONS(25),
    [sym_path] = ACTIONS(25),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_GT_GT] = ACTIONS(25),
    [anon_sym_LT_LT] = ACTIONS(25),
    [anon_sym_PIPE_GT] = ACTIONS(25),
    [anon_sym_LT_PIPE] = ACTIONS(25),
    [anon_sym_COLON_COLON] = ACTIONS(25),
    [anon_sym_DOT_DOT] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_EQ_EQ] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_COLON] = ACTIONS(27),
    [anon_sym_PIPE] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_AT] = ACTIONS(25),
    [anon_sym_DOLLAR] = ACTIONS(25),
    [anon_sym_AMP] = ACTIONS(25),
    [anon_sym_BQUOTE] = ACTIONS(25),
    [anon_sym_PERCENT] = ACTIONS(25),
    [sym_const_number] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(25),
    [anon_sym_CARET_] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_RBRACK] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(29),
    [sym_identifier] = ACTIONS(29),
    [sym_path] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(31),
    [anon_sym_GT_GT] = ACTIONS(33),
    [anon_sym_LT_LT] = ACTIONS(33),
    [anon_sym_PIPE_GT] = ACTIONS(33),
    [anon_sym_LT_PIPE] = ACTIONS(33),
    [anon_sym_COLON_COLON] = ACTIONS(33),
    [anon_sym_DOT_DOT] = ACTIONS(33),
    [anon_sym_GT_EQ] = ACTIONS(33),
    [anon_sym_LT_EQ] = ACTIONS(33),
    [anon_sym_EQ_EQ] = ACTIONS(33),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_COLON] = ACTIONS(41),
    [anon_sym_PIPE] = ACTIONS(41),
    [anon_sym_DOT] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(29),
    [anon_sym_DOLLAR] = ACTIONS(29),
    [anon_sym_AMP] = ACTIONS(29),
    [anon_sym_BQUOTE] = ACTIONS(29),
    [anon_sym_PERCENT] = ACTIONS(29),
    [sym_const_number] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(29),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(29),
    [anon_sym_CARET_] = ACTIONS(29),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(45),
    [anon_sym_LBRACK] = ACTIONS(45),
    [anon_sym_RBRACK] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(45),
    [anon_sym_RBRACE] = ACTIONS(45),
    [anon_sym_LPAREN] = ACTIONS(45),
    [anon_sym_RPAREN] = ACTIONS(45),
    [sym_identifier] = ACTIONS(45),
    [sym_path] = ACTIONS(45),
    [anon_sym_EQ] = ACTIONS(47),
    [anon_sym_GT_GT] = ACTIONS(45),
    [anon_sym_LT_LT] = ACTIONS(45),
    [anon_sym_PIPE_GT] = ACTIONS(45),
    [anon_sym_LT_PIPE] = ACTIONS(45),
    [anon_sym_COLON_COLON] = ACTIONS(45),
    [anon_sym_DOT_DOT] = ACTIONS(45),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(45),
    [anon_sym_STAR] = ACTIONS(45),
    [anon_sym_SLASH] = ACTIONS(47),
    [anon_sym_COLON] = ACTIONS(47),
    [anon_sym_PIPE] = ACTIONS(47),
    [anon_sym_DOT] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(45),
    [anon_sym_DOLLAR] = ACTIONS(45),
    [anon_sym_AMP] = ACTIONS(45),
    [anon_sym_BQUOTE] = ACTIONS(45),
    [anon_sym_PERCENT] = ACTIONS(45),
    [sym_const_number] = ACTIONS(45),
    [anon_sym_DQUOTE] = ACTIONS(45),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(45),
    [anon_sym_CARET_] = ACTIONS(45),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [anon_sym_RBRACK] = ACTIONS(49),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(49),
    [anon_sym_RPAREN] = ACTIONS(49),
    [sym_identifier] = ACTIONS(49),
    [sym_path] = ACTIONS(49),
    [anon_sym_EQ] = ACTIONS(51),
    [anon_sym_GT_GT] = ACTIONS(49),
    [anon_sym_LT_LT] = ACTIONS(49),
    [anon_sym_PIPE_GT] = ACTIONS(49),
    [anon_sym_LT_PIPE] = ACTIONS(49),
    [anon_sym_COLON_COLON] = ACTIONS(49),
    [anon_sym_DOT_DOT] = ACTIONS(49),
    [anon_sym_GT_EQ] = ACTIONS(49),
    [anon_sym_LT_EQ] = ACTIONS(49),
    [anon_sym_EQ_EQ] = ACTIONS(49),
    [anon_sym_PLUS] = ACTIONS(49),
    [anon_sym_DASH] = ACTIONS(49),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym_SLASH] = ACTIONS(51),
    [anon_sym_COLON] = ACTIONS(51),
    [anon_sym_PIPE] = ACTIONS(51),
    [anon_sym_DOT] = ACTIONS(51),
    [anon_sym_AT] = ACTIONS(49),
    [anon_sym_DOLLAR] = ACTIONS(49),
    [anon_sym_AMP] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_PERCENT] = ACTIONS(49),
    [sym_const_number] = ACTIONS(49),
    [anon_sym_DQUOTE] = ACTIONS(49),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(49),
    [anon_sym_CARET_] = ACTIONS(49),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(53),
    [anon_sym_RBRACK] = ACTIONS(53),
    [anon_sym_LBRACE] = ACTIONS(53),
    [anon_sym_RBRACE] = ACTIONS(53),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_RPAREN] = ACTIONS(53),
    [sym_identifier] = ACTIONS(53),
    [sym_path] = ACTIONS(53),
    [anon_sym_EQ] = ACTIONS(55),
    [anon_sym_GT_GT] = ACTIONS(53),
    [anon_sym_LT_LT] = ACTIONS(53),
    [anon_sym_PIPE_GT] = ACTIONS(53),
    [anon_sym_LT_PIPE] = ACTIONS(53),
    [anon_sym_COLON_COLON] = ACTIONS(53),
    [anon_sym_DOT_DOT] = ACTIONS(53),
    [anon_sym_GT_EQ] = ACTIONS(53),
    [anon_sym_LT_EQ] = ACTIONS(53),
    [anon_sym_EQ_EQ] = ACTIONS(53),
    [anon_sym_PLUS] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(53),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym_SLASH] = ACTIONS(55),
    [anon_sym_COLON] = ACTIONS(55),
    [anon_sym_PIPE] = ACTIONS(55),
    [anon_sym_DOT] = ACTIONS(55),
    [anon_sym_AT] = ACTIONS(53),
    [anon_sym_DOLLAR] = ACTIONS(53),
    [anon_sym_AMP] = ACTIONS(53),
    [anon_sym_BQUOTE] = ACTIONS(53),
    [anon_sym_PERCENT] = ACTIONS(53),
    [sym_const_number] = ACTIONS(53),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(53),
    [anon_sym_CARET_] = ACTIONS(53),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(57),
    [anon_sym_LBRACK] = ACTIONS(57),
    [anon_sym_RBRACK] = ACTIONS(57),
    [anon_sym_LBRACE] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(57),
    [anon_sym_LPAREN] = ACTIONS(57),
    [anon_sym_RPAREN] = ACTIONS(57),
    [sym_identifier] = ACTIONS(57),
    [sym_path] = ACTIONS(57),
    [anon_sym_EQ] = ACTIONS(59),
    [anon_sym_GT_GT] = ACTIONS(57),
    [anon_sym_LT_LT] = ACTIONS(57),
    [anon_sym_PIPE_GT] = ACTIONS(57),
    [anon_sym_LT_PIPE] = ACTIONS(57),
    [anon_sym_COLON_COLON] = ACTIONS(57),
    [anon_sym_DOT_DOT] = ACTIONS(57),
    [anon_sym_GT_EQ] = ACTIONS(57),
    [anon_sym_LT_EQ] = ACTIONS(57),
    [anon_sym_EQ_EQ] = ACTIONS(57),
    [anon_sym_PLUS] = ACTIONS(57),
    [anon_sym_DASH] = ACTIONS(57),
    [anon_sym_STAR] = ACTIONS(57),
    [anon_sym_SLASH] = ACTIONS(59),
    [anon_sym_COLON] = ACTIONS(59),
    [anon_sym_PIPE] = ACTIONS(59),
    [anon_sym_DOT] = ACTIONS(59),
    [anon_sym_AT] = ACTIONS(57),
    [anon_sym_DOLLAR] = ACTIONS(57),
    [anon_sym_AMP] = ACTIONS(57),
    [anon_sym_BQUOTE] = ACTIONS(57),
    [anon_sym_PERCENT] = ACTIONS(57),
    [sym_const_number] = ACTIONS(57),
    [anon_sym_DQUOTE] = ACTIONS(57),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(57),
    [anon_sym_CARET_] = ACTIONS(57),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(61),
    [anon_sym_LPAREN] = ACTIONS(61),
    [anon_sym_RPAREN] = ACTIONS(61),
    [sym_identifier] = ACTIONS(61),
    [sym_path] = ACTIONS(61),
    [anon_sym_EQ] = ACTIONS(63),
    [anon_sym_GT_GT] = ACTIONS(61),
    [anon_sym_LT_LT] = ACTIONS(61),
    [anon_sym_PIPE_GT] = ACTIONS(61),
    [anon_sym_LT_PIPE] = ACTIONS(61),
    [anon_sym_COLON_COLON] = ACTIONS(61),
    [anon_sym_DOT_DOT] = ACTIONS(61),
    [anon_sym_GT_EQ] = ACTIONS(61),
    [anon_sym_LT_EQ] = ACTIONS(61),
    [anon_sym_EQ_EQ] = ACTIONS(61),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_STAR] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [anon_sym_COLON] = ACTIONS(63),
    [anon_sym_PIPE] = ACTIONS(63),
    [anon_sym_DOT] = ACTIONS(63),
    [anon_sym_AT] = ACTIONS(61),
    [anon_sym_DOLLAR] = ACTIONS(61),
    [anon_sym_AMP] = ACTIONS(61),
    [anon_sym_BQUOTE] = ACTIONS(61),
    [anon_sym_PERCENT] = ACTIONS(61),
    [sym_const_number] = ACTIONS(61),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(61),
    [anon_sym_CARET_] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(65),
    [anon_sym_RBRACK] = ACTIONS(65),
    [anon_sym_LBRACE] = ACTIONS(65),
    [anon_sym_RBRACE] = ACTIONS(65),
    [anon_sym_LPAREN] = ACTIONS(65),
    [anon_sym_RPAREN] = ACTIONS(65),
    [sym_identifier] = ACTIONS(65),
    [sym_path] = ACTIONS(65),
    [anon_sym_EQ] = ACTIONS(67),
    [anon_sym_GT_GT] = ACTIONS(65),
    [anon_sym_LT_LT] = ACTIONS(65),
    [anon_sym_PIPE_GT] = ACTIONS(65),
    [anon_sym_LT_PIPE] = ACTIONS(65),
    [anon_sym_COLON_COLON] = ACTIONS(65),
    [anon_sym_DOT_DOT] = ACTIONS(65),
    [anon_sym_GT_EQ] = ACTIONS(65),
    [anon_sym_LT_EQ] = ACTIONS(65),
    [anon_sym_EQ_EQ] = ACTIONS(65),
    [anon_sym_PLUS] = ACTIONS(65),
    [anon_sym_DASH] = ACTIONS(65),
    [anon_sym_STAR] = ACTIONS(65),
    [anon_sym_SLASH] = ACTIONS(67),
    [anon_sym_COLON] = ACTIONS(67),
    [anon_sym_PIPE] = ACTIONS(67),
    [anon_sym_DOT] = ACTIONS(67),
    [anon_sym_AT] = ACTIONS(65),
    [anon_sym_DOLLAR] = ACTIONS(65),
    [anon_sym_AMP] = ACTIONS(65),
    [anon_sym_BQUOTE] = ACTIONS(65),
    [anon_sym_PERCENT] = ACTIONS(65),
    [sym_const_number] = ACTIONS(65),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(65),
    [anon_sym_CARET_] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [anon_sym_LBRACK] = ACTIONS(69),
    [anon_sym_RBRACK] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(69),
    [anon_sym_RBRACE] = ACTIONS(69),
    [anon_sym_LPAREN] = ACTIONS(69),
    [anon_sym_RPAREN] = ACTIONS(69),
    [sym_identifier] = ACTIONS(69),
    [sym_path] = ACTIONS(69),
    [anon_sym_EQ] = ACTIONS(71),
    [anon_sym_GT_GT] = ACTIONS(69),
    [anon_sym_LT_LT] = ACTIONS(69),
    [anon_sym_PIPE_GT] = ACTIONS(69),
    [anon_sym_LT_PIPE] = ACTIONS(69),
    [anon_sym_COLON_COLON] = ACTIONS(69),
    [anon_sym_DOT_DOT] = ACTIONS(69),
    [anon_sym_GT_EQ] = ACTIONS(69),
    [anon_sym_LT_EQ] = ACTIONS(69),
    [anon_sym_EQ_EQ] = ACTIONS(69),
    [anon_sym_PLUS] = ACTIONS(69),
    [anon_sym_DASH] = ACTIONS(69),
    [anon_sym_STAR] = ACTIONS(69),
    [anon_sym_SLASH] = ACTIONS(71),
    [anon_sym_COLON] = ACTIONS(71),
    [anon_sym_PIPE] = ACTIONS(71),
    [anon_sym_DOT] = ACTIONS(71),
    [anon_sym_AT] = ACTIONS(69),
    [anon_sym_DOLLAR] = ACTIONS(69),
    [anon_sym_AMP] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(69),
    [anon_sym_PERCENT] = ACTIONS(69),
    [sym_const_number] = ACTIONS(69),
    [anon_sym_DQUOTE] = ACTIONS(69),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(69),
    [anon_sym_CARET_] = ACTIONS(69),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(73),
    [anon_sym_RBRACK] = ACTIONS(73),
    [anon_sym_LBRACE] = ACTIONS(73),
    [anon_sym_RBRACE] = ACTIONS(73),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_RPAREN] = ACTIONS(73),
    [sym_identifier] = ACTIONS(73),
    [sym_path] = ACTIONS(73),
    [anon_sym_EQ] = ACTIONS(75),
    [anon_sym_GT_GT] = ACTIONS(73),
    [anon_sym_LT_LT] = ACTIONS(73),
    [anon_sym_PIPE_GT] = ACTIONS(73),
    [anon_sym_LT_PIPE] = ACTIONS(73),
    [anon_sym_COLON_COLON] = ACTIONS(73),
    [anon_sym_DOT_DOT] = ACTIONS(73),
    [anon_sym_GT_EQ] = ACTIONS(73),
    [anon_sym_LT_EQ] = ACTIONS(73),
    [anon_sym_EQ_EQ] = ACTIONS(73),
    [anon_sym_PLUS] = ACTIONS(73),
    [anon_sym_DASH] = ACTIONS(73),
    [anon_sym_STAR] = ACTIONS(73),
    [anon_sym_SLASH] = ACTIONS(75),
    [anon_sym_COLON] = ACTIONS(75),
    [anon_sym_PIPE] = ACTIONS(75),
    [anon_sym_DOT] = ACTIONS(75),
    [anon_sym_AT] = ACTIONS(73),
    [anon_sym_DOLLAR] = ACTIONS(73),
    [anon_sym_AMP] = ACTIONS(73),
    [anon_sym_BQUOTE] = ACTIONS(73),
    [anon_sym_PERCENT] = ACTIONS(73),
    [sym_const_number] = ACTIONS(73),
    [anon_sym_DQUOTE] = ACTIONS(73),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(73),
    [anon_sym_CARET_] = ACTIONS(73),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(77),
    [anon_sym_LBRACK] = ACTIONS(77),
    [anon_sym_RBRACK] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(77),
    [anon_sym_RBRACE] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(77),
    [anon_sym_RPAREN] = ACTIONS(77),
    [sym_identifier] = ACTIONS(77),
    [sym_path] = ACTIONS(77),
    [anon_sym_EQ] = ACTIONS(79),
    [anon_sym_GT_GT] = ACTIONS(77),
    [anon_sym_LT_LT] = ACTIONS(77),
    [anon_sym_PIPE_GT] = ACTIONS(77),
    [anon_sym_LT_PIPE] = ACTIONS(77),
    [anon_sym_COLON_COLON] = ACTIONS(77),
    [anon_sym_DOT_DOT] = ACTIONS(77),
    [anon_sym_GT_EQ] = ACTIONS(77),
    [anon_sym_LT_EQ] = ACTIONS(77),
    [anon_sym_EQ_EQ] = ACTIONS(77),
    [anon_sym_PLUS] = ACTIONS(77),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_STAR] = ACTIONS(77),
    [anon_sym_SLASH] = ACTIONS(79),
    [anon_sym_COLON] = ACTIONS(79),
    [anon_sym_PIPE] = ACTIONS(79),
    [anon_sym_DOT] = ACTIONS(79),
    [anon_sym_AT] = ACTIONS(77),
    [anon_sym_DOLLAR] = ACTIONS(77),
    [anon_sym_AMP] = ACTIONS(77),
    [anon_sym_BQUOTE] = ACTIONS(77),
    [anon_sym_PERCENT] = ACTIONS(77),
    [sym_const_number] = ACTIONS(77),
    [anon_sym_DQUOTE] = ACTIONS(77),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(77),
    [anon_sym_CARET_] = ACTIONS(77),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(81),
    [sym_identifier] = ACTIONS(81),
    [sym_path] = ACTIONS(81),
    [anon_sym_EQ] = ACTIONS(83),
    [anon_sym_GT_GT] = ACTIONS(33),
    [anon_sym_LT_LT] = ACTIONS(33),
    [anon_sym_PIPE_GT] = ACTIONS(33),
    [anon_sym_LT_PIPE] = ACTIONS(33),
    [anon_sym_COLON_COLON] = ACTIONS(33),
    [anon_sym_DOT_DOT] = ACTIONS(33),
    [anon_sym_GT_EQ] = ACTIONS(33),
    [anon_sym_LT_EQ] = ACTIONS(33),
    [anon_sym_EQ_EQ] = ACTIONS(33),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_COLON] = ACTIONS(41),
    [anon_sym_PIPE] = ACTIONS(41),
    [anon_sym_DOT] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(81),
    [anon_sym_DOLLAR] = ACTIONS(81),
    [anon_sym_AMP] = ACTIONS(81),
    [anon_sym_BQUOTE] = ACTIONS(81),
    [anon_sym_PERCENT] = ACTIONS(81),
    [sym_const_number] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(81),
    [anon_sym_CARET_] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(81),
    [sym_identifier] = ACTIONS(81),
    [sym_path] = ACTIONS(81),
    [anon_sym_EQ] = ACTIONS(83),
    [anon_sym_GT_GT] = ACTIONS(81),
    [anon_sym_LT_LT] = ACTIONS(81),
    [anon_sym_PIPE_GT] = ACTIONS(81),
    [anon_sym_LT_PIPE] = ACTIONS(81),
    [anon_sym_COLON_COLON] = ACTIONS(81),
    [anon_sym_DOT_DOT] = ACTIONS(81),
    [anon_sym_GT_EQ] = ACTIONS(81),
    [anon_sym_LT_EQ] = ACTIONS(81),
    [anon_sym_EQ_EQ] = ACTIONS(81),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_COLON] = ACTIONS(41),
    [anon_sym_PIPE] = ACTIONS(41),
    [anon_sym_DOT] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(81),
    [anon_sym_DOLLAR] = ACTIONS(81),
    [anon_sym_AMP] = ACTIONS(81),
    [anon_sym_BQUOTE] = ACTIONS(81),
    [anon_sym_PERCENT] = ACTIONS(81),
    [sym_const_number] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(81),
    [anon_sym_CARET_] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(81),
    [sym_identifier] = ACTIONS(81),
    [sym_path] = ACTIONS(81),
    [anon_sym_EQ] = ACTIONS(83),
    [anon_sym_GT_GT] = ACTIONS(81),
    [anon_sym_LT_LT] = ACTIONS(81),
    [anon_sym_PIPE_GT] = ACTIONS(81),
    [anon_sym_LT_PIPE] = ACTIONS(81),
    [anon_sym_COLON_COLON] = ACTIONS(81),
    [anon_sym_DOT_DOT] = ACTIONS(81),
    [anon_sym_GT_EQ] = ACTIONS(81),
    [anon_sym_LT_EQ] = ACTIONS(81),
    [anon_sym_EQ_EQ] = ACTIONS(81),
    [anon_sym_PLUS] = ACTIONS(81),
    [anon_sym_DASH] = ACTIONS(81),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_COLON] = ACTIONS(41),
    [anon_sym_PIPE] = ACTIONS(41),
    [anon_sym_DOT] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(81),
    [anon_sym_DOLLAR] = ACTIONS(81),
    [anon_sym_AMP] = ACTIONS(81),
    [anon_sym_BQUOTE] = ACTIONS(81),
    [anon_sym_PERCENT] = ACTIONS(81),
    [sym_const_number] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(81),
    [anon_sym_CARET_] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(16)] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(81),
    [sym_identifier] = ACTIONS(81),
    [sym_path] = ACTIONS(81),
    [anon_sym_EQ] = ACTIONS(83),
    [anon_sym_GT_GT] = ACTIONS(81),
    [anon_sym_LT_LT] = ACTIONS(81),
    [anon_sym_PIPE_GT] = ACTIONS(81),
    [anon_sym_LT_PIPE] = ACTIONS(81),
    [anon_sym_COLON_COLON] = ACTIONS(81),
    [anon_sym_DOT_DOT] = ACTIONS(81),
    [anon_sym_GT_EQ] = ACTIONS(81),
    [anon_sym_LT_EQ] = ACTIONS(81),
    [anon_sym_EQ_EQ] = ACTIONS(81),
    [anon_sym_PLUS] = ACTIONS(81),
    [anon_sym_DASH] = ACTIONS(81),
    [anon_sym_STAR] = ACTIONS(81),
    [anon_sym_SLASH] = ACTIONS(83),
    [anon_sym_COLON] = ACTIONS(41),
    [anon_sym_PIPE] = ACTIONS(41),
    [anon_sym_DOT] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(81),
    [anon_sym_DOLLAR] = ACTIONS(81),
    [anon_sym_AMP] = ACTIONS(81),
    [anon_sym_BQUOTE] = ACTIONS(81),
    [anon_sym_PERCENT] = ACTIONS(81),
    [sym_const_number] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(81),
    [anon_sym_CARET_] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(17)] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(81),
    [sym_identifier] = ACTIONS(81),
    [sym_path] = ACTIONS(81),
    [anon_sym_EQ] = ACTIONS(83),
    [anon_sym_GT_GT] = ACTIONS(81),
    [anon_sym_LT_LT] = ACTIONS(81),
    [anon_sym_PIPE_GT] = ACTIONS(81),
    [anon_sym_LT_PIPE] = ACTIONS(81),
    [anon_sym_COLON_COLON] = ACTIONS(81),
    [anon_sym_DOT_DOT] = ACTIONS(81),
    [anon_sym_GT_EQ] = ACTIONS(81),
    [anon_sym_LT_EQ] = ACTIONS(81),
    [anon_sym_EQ_EQ] = ACTIONS(81),
    [anon_sym_PLUS] = ACTIONS(81),
    [anon_sym_DASH] = ACTIONS(81),
    [anon_sym_STAR] = ACTIONS(81),
    [anon_sym_SLASH] = ACTIONS(83),
    [anon_sym_COLON] = ACTIONS(83),
    [anon_sym_PIPE] = ACTIONS(83),
    [anon_sym_DOT] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(81),
    [anon_sym_DOLLAR] = ACTIONS(81),
    [anon_sym_AMP] = ACTIONS(81),
    [anon_sym_BQUOTE] = ACTIONS(81),
    [anon_sym_PERCENT] = ACTIONS(81),
    [sym_const_number] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(81),
    [anon_sym_CARET_] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(18)] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(81),
    [sym_identifier] = ACTIONS(81),
    [sym_path] = ACTIONS(81),
    [anon_sym_EQ] = ACTIONS(83),
    [anon_sym_GT_GT] = ACTIONS(81),
    [anon_sym_LT_LT] = ACTIONS(81),
    [anon_sym_PIPE_GT] = ACTIONS(81),
    [anon_sym_LT_PIPE] = ACTIONS(81),
    [anon_sym_COLON_COLON] = ACTIONS(81),
    [anon_sym_DOT_DOT] = ACTIONS(81),
    [anon_sym_GT_EQ] = ACTIONS(81),
    [anon_sym_LT_EQ] = ACTIONS(81),
    [anon_sym_EQ_EQ] = ACTIONS(81),
    [anon_sym_PLUS] = ACTIONS(81),
    [anon_sym_DASH] = ACTIONS(81),
    [anon_sym_STAR] = ACTIONS(81),
    [anon_sym_SLASH] = ACTIONS(83),
    [anon_sym_COLON] = ACTIONS(83),
    [anon_sym_PIPE] = ACTIONS(83),
    [anon_sym_DOT] = ACTIONS(83),
    [anon_sym_AT] = ACTIONS(81),
    [anon_sym_DOLLAR] = ACTIONS(81),
    [anon_sym_AMP] = ACTIONS(81),
    [anon_sym_BQUOTE] = ACTIONS(81),
    [anon_sym_PERCENT] = ACTIONS(81),
    [sym_const_number] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(81),
    [anon_sym_CARET_] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(19)] = {
    [ts_builtin_sym_end] = ACTIONS(85),
    [anon_sym_LBRACK] = ACTIONS(85),
    [anon_sym_RBRACK] = ACTIONS(85),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_RBRACE] = ACTIONS(85),
    [anon_sym_LPAREN] = ACTIONS(85),
    [anon_sym_RPAREN] = ACTIONS(85),
    [sym_identifier] = ACTIONS(85),
    [sym_path] = ACTIONS(85),
    [anon_sym_EQ] = ACTIONS(87),
    [anon_sym_GT_GT] = ACTIONS(85),
    [anon_sym_LT_LT] = ACTIONS(85),
    [anon_sym_PIPE_GT] = ACTIONS(85),
    [anon_sym_LT_PIPE] = ACTIONS(85),
    [anon_sym_COLON_COLON] = ACTIONS(85),
    [anon_sym_DOT_DOT] = ACTIONS(85),
    [anon_sym_GT_EQ] = ACTIONS(85),
    [anon_sym_LT_EQ] = ACTIONS(85),
    [anon_sym_EQ_EQ] = ACTIONS(85),
    [anon_sym_PLUS] = ACTIONS(85),
    [anon_sym_DASH] = ACTIONS(85),
    [anon_sym_STAR] = ACTIONS(85),
    [anon_sym_SLASH] = ACTIONS(87),
    [anon_sym_COLON] = ACTIONS(87),
    [anon_sym_PIPE] = ACTIONS(87),
    [anon_sym_DOT] = ACTIONS(87),
    [anon_sym_AT] = ACTIONS(85),
    [anon_sym_DOLLAR] = ACTIONS(85),
    [anon_sym_AMP] = ACTIONS(85),
    [anon_sym_BQUOTE] = ACTIONS(85),
    [anon_sym_PERCENT] = ACTIONS(85),
    [sym_const_number] = ACTIONS(85),
    [anon_sym_DQUOTE] = ACTIONS(85),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(85),
    [anon_sym_CARET_] = ACTIONS(85),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(20)] = {
    [ts_builtin_sym_end] = ACTIONS(89),
    [anon_sym_LBRACK] = ACTIONS(89),
    [anon_sym_RBRACK] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(89),
    [anon_sym_RPAREN] = ACTIONS(89),
    [sym_identifier] = ACTIONS(89),
    [sym_path] = ACTIONS(89),
    [anon_sym_EQ] = ACTIONS(91),
    [anon_sym_GT_GT] = ACTIONS(89),
    [anon_sym_LT_LT] = ACTIONS(89),
    [anon_sym_PIPE_GT] = ACTIONS(89),
    [anon_sym_LT_PIPE] = ACTIONS(89),
    [anon_sym_COLON_COLON] = ACTIONS(89),
    [anon_sym_DOT_DOT] = ACTIONS(89),
    [anon_sym_GT_EQ] = ACTIONS(89),
    [anon_sym_LT_EQ] = ACTIONS(89),
    [anon_sym_EQ_EQ] = ACTIONS(89),
    [anon_sym_PLUS] = ACTIONS(89),
    [anon_sym_DASH] = ACTIONS(89),
    [anon_sym_STAR] = ACTIONS(89),
    [anon_sym_SLASH] = ACTIONS(91),
    [anon_sym_COLON] = ACTIONS(91),
    [anon_sym_PIPE] = ACTIONS(91),
    [anon_sym_DOT] = ACTIONS(91),
    [anon_sym_AT] = ACTIONS(89),
    [anon_sym_DOLLAR] = ACTIONS(89),
    [anon_sym_AMP] = ACTIONS(89),
    [anon_sym_BQUOTE] = ACTIONS(89),
    [anon_sym_PERCENT] = ACTIONS(89),
    [sym_const_number] = ACTIONS(89),
    [anon_sym_DQUOTE] = ACTIONS(89),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(89),
    [anon_sym_CARET_] = ACTIONS(89),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(21)] = {
    [ts_builtin_sym_end] = ACTIONS(93),
    [anon_sym_LBRACK] = ACTIONS(93),
    [anon_sym_RBRACK] = ACTIONS(93),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_RBRACE] = ACTIONS(93),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_RPAREN] = ACTIONS(93),
    [sym_identifier] = ACTIONS(93),
    [sym_path] = ACTIONS(93),
    [anon_sym_EQ] = ACTIONS(95),
    [anon_sym_GT_GT] = ACTIONS(93),
    [anon_sym_LT_LT] = ACTIONS(93),
    [anon_sym_PIPE_GT] = ACTIONS(93),
    [anon_sym_LT_PIPE] = ACTIONS(93),
    [anon_sym_COLON_COLON] = ACTIONS(93),
    [anon_sym_DOT_DOT] = ACTIONS(93),
    [anon_sym_GT_EQ] = ACTIONS(93),
    [anon_sym_LT_EQ] = ACTIONS(93),
    [anon_sym_EQ_EQ] = ACTIONS(93),
    [anon_sym_PLUS] = ACTIONS(93),
    [anon_sym_DASH] = ACTIONS(93),
    [anon_sym_STAR] = ACTIONS(93),
    [anon_sym_SLASH] = ACTIONS(95),
    [anon_sym_COLON] = ACTIONS(95),
    [anon_sym_PIPE] = ACTIONS(95),
    [anon_sym_DOT] = ACTIONS(95),
    [anon_sym_AT] = ACTIONS(93),
    [anon_sym_DOLLAR] = ACTIONS(93),
    [anon_sym_AMP] = ACTIONS(93),
    [anon_sym_BQUOTE] = ACTIONS(93),
    [anon_sym_PERCENT] = ACTIONS(93),
    [sym_const_number] = ACTIONS(93),
    [anon_sym_DQUOTE] = ACTIONS(93),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(93),
    [anon_sym_CARET_] = ACTIONS(93),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(22)] = {
    [ts_builtin_sym_end] = ACTIONS(97),
    [anon_sym_LBRACK] = ACTIONS(97),
    [anon_sym_RBRACK] = ACTIONS(97),
    [anon_sym_LBRACE] = ACTIONS(97),
    [anon_sym_RBRACE] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(97),
    [anon_sym_RPAREN] = ACTIONS(97),
    [sym_identifier] = ACTIONS(97),
    [sym_path] = ACTIONS(97),
    [anon_sym_EQ] = ACTIONS(99),
    [anon_sym_GT_GT] = ACTIONS(97),
    [anon_sym_LT_LT] = ACTIONS(97),
    [anon_sym_PIPE_GT] = ACTIONS(97),
    [anon_sym_LT_PIPE] = ACTIONS(97),
    [anon_sym_COLON_COLON] = ACTIONS(97),
    [anon_sym_DOT_DOT] = ACTIONS(97),
    [anon_sym_GT_EQ] = ACTIONS(97),
    [anon_sym_LT_EQ] = ACTIONS(97),
    [anon_sym_EQ_EQ] = ACTIONS(97),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_DASH] = ACTIONS(97),
    [anon_sym_STAR] = ACTIONS(97),
    [anon_sym_SLASH] = ACTIONS(99),
    [anon_sym_COLON] = ACTIONS(99),
    [anon_sym_PIPE] = ACTIONS(99),
    [anon_sym_DOT] = ACTIONS(99),
    [anon_sym_AT] = ACTIONS(97),
    [anon_sym_DOLLAR] = ACTIONS(97),
    [anon_sym_AMP] = ACTIONS(97),
    [anon_sym_BQUOTE] = ACTIONS(97),
    [anon_sym_PERCENT] = ACTIONS(97),
    [sym_const_number] = ACTIONS(97),
    [anon_sym_DQUOTE] = ACTIONS(97),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(97),
    [anon_sym_CARET_] = ACTIONS(97),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(23)] = {
    [ts_builtin_sym_end] = ACTIONS(101),
    [anon_sym_LBRACK] = ACTIONS(101),
    [anon_sym_RBRACK] = ACTIONS(101),
    [anon_sym_LBRACE] = ACTIONS(101),
    [anon_sym_RBRACE] = ACTIONS(101),
    [anon_sym_LPAREN] = ACTIONS(101),
    [anon_sym_RPAREN] = ACTIONS(101),
    [sym_identifier] = ACTIONS(101),
    [sym_path] = ACTIONS(101),
    [anon_sym_EQ] = ACTIONS(103),
    [anon_sym_GT_GT] = ACTIONS(101),
    [anon_sym_LT_LT] = ACTIONS(101),
    [anon_sym_PIPE_GT] = ACTIONS(101),
    [anon_sym_LT_PIPE] = ACTIONS(101),
    [anon_sym_COLON_COLON] = ACTIONS(101),
    [anon_sym_DOT_DOT] = ACTIONS(101),
    [anon_sym_GT_EQ] = ACTIONS(101),
    [anon_sym_LT_EQ] = ACTIONS(101),
    [anon_sym_EQ_EQ] = ACTIONS(101),
    [anon_sym_PLUS] = ACTIONS(101),
    [anon_sym_DASH] = ACTIONS(101),
    [anon_sym_STAR] = ACTIONS(101),
    [anon_sym_SLASH] = ACTIONS(103),
    [anon_sym_COLON] = ACTIONS(103),
    [anon_sym_PIPE] = ACTIONS(103),
    [anon_sym_DOT] = ACTIONS(103),
    [anon_sym_AT] = ACTIONS(101),
    [anon_sym_DOLLAR] = ACTIONS(101),
    [anon_sym_AMP] = ACTIONS(101),
    [anon_sym_BQUOTE] = ACTIONS(101),
    [anon_sym_PERCENT] = ACTIONS(101),
    [sym_const_number] = ACTIONS(101),
    [anon_sym_DQUOTE] = ACTIONS(101),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(101),
    [anon_sym_CARET_] = ACTIONS(101),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(24)] = {
    [ts_builtin_sym_end] = ACTIONS(105),
    [anon_sym_LBRACK] = ACTIONS(105),
    [anon_sym_RBRACK] = ACTIONS(105),
    [anon_sym_LBRACE] = ACTIONS(105),
    [anon_sym_RBRACE] = ACTIONS(105),
    [anon_sym_LPAREN] = ACTIONS(105),
    [anon_sym_RPAREN] = ACTIONS(105),
    [sym_identifier] = ACTIONS(105),
    [sym_path] = ACTIONS(105),
    [anon_sym_EQ] = ACTIONS(107),
    [anon_sym_GT_GT] = ACTIONS(105),
    [anon_sym_LT_LT] = ACTIONS(105),
    [anon_sym_PIPE_GT] = ACTIONS(105),
    [anon_sym_LT_PIPE] = ACTIONS(105),
    [anon_sym_COLON_COLON] = ACTIONS(105),
    [anon_sym_DOT_DOT] = ACTIONS(105),
    [anon_sym_GT_EQ] = ACTIONS(105),
    [anon_sym_LT_EQ] = ACTIONS(105),
    [anon_sym_EQ_EQ] = ACTIONS(105),
    [anon_sym_PLUS] = ACTIONS(105),
    [anon_sym_DASH] = ACTIONS(105),
    [anon_sym_STAR] = ACTIONS(105),
    [anon_sym_SLASH] = ACTIONS(107),
    [anon_sym_COLON] = ACTIONS(107),
    [anon_sym_PIPE] = ACTIONS(107),
    [anon_sym_DOT] = ACTIONS(107),
    [anon_sym_AT] = ACTIONS(105),
    [anon_sym_DOLLAR] = ACTIONS(105),
    [anon_sym_AMP] = ACTIONS(105),
    [anon_sym_BQUOTE] = ACTIONS(105),
    [anon_sym_PERCENT] = ACTIONS(105),
    [sym_const_number] = ACTIONS(105),
    [anon_sym_DQUOTE] = ACTIONS(105),
    [anon_sym_COMMA_COMMA_COMMA] = ACTIONS(105),
    [anon_sym_CARET_] = ACTIONS(105),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_LBRACK,
    ACTIONS(114), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(126), 1,
      sym_const_number,
    ACTIONS(129), 1,
      anon_sym_DQUOTE,
    ACTIONS(132), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(135), 1,
      anon_sym_CARET_,
    STATE(25), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(120), 2,
      sym_identifier,
      sym_path,
    STATE(4), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(109), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    ACTIONS(123), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_PERCENT,
    STATE(3), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [58] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(138), 1,
      anon_sym_RBRACK,
    STATE(30), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(13), 2,
      sym_identifier,
      sym_path,
    STATE(4), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_PERCENT,
    STATE(3), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [113] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(13), 2,
      sym_identifier,
      sym_path,
    STATE(4), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_PERCENT,
    STATE(3), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [168] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(13), 2,
      sym_identifier,
      sym_path,
    STATE(4), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_PERCENT,
    STATE(3), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [223] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(144), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(13), 2,
      sym_identifier,
      sym_path,
    STATE(4), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_PERCENT,
    STATE(3), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [278] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(146), 1,
      anon_sym_RBRACK,
    STATE(25), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(13), 2,
      sym_identifier,
      sym_path,
    STATE(4), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_PERCENT,
    STATE(3), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [333] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(148), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(13), 2,
      sym_identifier,
      sym_path,
    STATE(4), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_PERCENT,
    STATE(3), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [388] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(150), 1,
      anon_sym_RBRACE,
    STATE(28), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(13), 2,
      sym_identifier,
      sym_path,
    STATE(4), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_PERCENT,
    STATE(3), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [443] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(152), 2,
      sym_identifier,
      sym_path,
    STATE(4), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_PERCENT,
    STATE(18), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [492] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(154), 2,
      sym_identifier,
      sym_path,
    STATE(4), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_PERCENT,
    STATE(16), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [541] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(156), 2,
      sym_identifier,
      sym_path,
    STATE(4), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_PERCENT,
    STATE(8), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [590] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(158), 2,
      sym_identifier,
      sym_path,
    STATE(4), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_PERCENT,
    STATE(17), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [639] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(160), 2,
      sym_identifier,
      sym_path,
    STATE(4), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_PERCENT,
    STATE(13), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [688] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(162), 2,
      sym_identifier,
      sym_path,
    STATE(4), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_PERCENT,
    STATE(14), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [737] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_const_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_COMMA_COMMA_COMMA,
    ACTIONS(23), 1,
      anon_sym_CARET_,
    ACTIONS(164), 2,
      sym_identifier,
      sym_path,
    STATE(4), 3,
      sym_const_string,
      sym_paragrapth,
      sym_cat_string,
    ACTIONS(15), 5,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_AMP,
      anon_sym_BQUOTE,
      anon_sym_PERCENT,
    STATE(15), 6,
      sym_list,
      sym_curly_list,
      sym_group,
      sym_binary_expression,
      sym_unary_expression,
      sym_const_value,
  [786] = 5,
    ACTIONS(166), 1,
      aux_sym_cat_string_token2,
    ACTIONS(168), 1,
      anon_sym__,
    ACTIONS(170), 1,
      anon_sym__CARET,
    ACTIONS(172), 1,
      sym_comment,
    STATE(44), 1,
      aux_sym_cat_string_repeat1,
  [802] = 5,
    ACTIONS(166), 1,
      aux_sym_cat_string_token2,
    ACTIONS(168), 1,
      anon_sym__,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym__CARET,
    STATE(44), 1,
      aux_sym_cat_string_repeat1,
  [818] = 5,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_LF_COMMA_COMMA_COMMA,
    ACTIONS(178), 1,
      sym_paragrapth_head,
    ACTIONS(180), 1,
      sym_paragrapth_content,
    STATE(49), 1,
      aux_sym_paragrapth_repeat1,
  [834] = 5,
    ACTIONS(168), 1,
      anon_sym__,
    ACTIONS(170), 1,
      anon_sym__CARET,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(182), 1,
      aux_sym_cat_string_token2,
    STATE(41), 1,
      aux_sym_cat_string_repeat1,
  [850] = 5,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(184), 1,
      aux_sym_cat_string_token2,
    ACTIONS(187), 1,
      anon_sym__,
    ACTIONS(190), 1,
      anon_sym__CARET,
    STATE(44), 1,
      aux_sym_cat_string_repeat1,
  [866] = 5,
    ACTIONS(168), 1,
      anon_sym__,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(192), 1,
      aux_sym_cat_string_token2,
    ACTIONS(194), 1,
      anon_sym__CARET,
    STATE(40), 1,
      aux_sym_cat_string_repeat1,
  [882] = 4,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_LF_COMMA_COMMA_COMMA,
    ACTIONS(198), 1,
      sym_paragrapth_content,
    STATE(48), 1,
      aux_sym_paragrapth_repeat1,
  [895] = 4,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_LF_COMMA_COMMA_COMMA,
    ACTIONS(202), 1,
      sym_paragrapth_content,
    STATE(47), 1,
      aux_sym_paragrapth_repeat1,
  [908] = 4,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_LF_COMMA_COMMA_COMMA,
    ACTIONS(207), 1,
      sym_paragrapth_content,
    STATE(47), 1,
      aux_sym_paragrapth_repeat1,
  [921] = 4,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(207), 1,
      sym_paragrapth_content,
    ACTIONS(209), 1,
      anon_sym_LF_COMMA_COMMA_COMMA,
    STATE(47), 1,
      aux_sym_paragrapth_repeat1,
  [934] = 2,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(190), 3,
      aux_sym_cat_string_token2,
      anon_sym__,
      anon_sym__CARET,
  [943] = 3,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym_paragrapth_head,
    ACTIONS(213), 1,
      aux_sym_cat_string_token1,
  [953] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_DQUOTE,
  [960] = 2,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_LF,
  [967] = 2,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(219), 1,
      aux_sym_const_string_token1,
  [974] = 2,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(221), 1,
      aux_sym_cat_string_token3,
  [981] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
  [988] = 2,
    ACTIONS(172), 1,
      sym_comment,
    ACTIONS(225), 1,
      aux_sym_cat_string_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(25)] = 0,
  [SMALL_STATE(26)] = 58,
  [SMALL_STATE(27)] = 113,
  [SMALL_STATE(28)] = 168,
  [SMALL_STATE(29)] = 223,
  [SMALL_STATE(30)] = 278,
  [SMALL_STATE(31)] = 333,
  [SMALL_STATE(32)] = 388,
  [SMALL_STATE(33)] = 443,
  [SMALL_STATE(34)] = 492,
  [SMALL_STATE(35)] = 541,
  [SMALL_STATE(36)] = 590,
  [SMALL_STATE(37)] = 639,
  [SMALL_STATE(38)] = 688,
  [SMALL_STATE(39)] = 737,
  [SMALL_STATE(40)] = 786,
  [SMALL_STATE(41)] = 802,
  [SMALL_STATE(42)] = 818,
  [SMALL_STATE(43)] = 834,
  [SMALL_STATE(44)] = 850,
  [SMALL_STATE(45)] = 866,
  [SMALL_STATE(46)] = 882,
  [SMALL_STATE(47)] = 895,
  [SMALL_STATE(48)] = 908,
  [SMALL_STATE(49)] = 921,
  [SMALL_STATE(50)] = 934,
  [SMALL_STATE(51)] = 943,
  [SMALL_STATE(52)] = 953,
  [SMALL_STATE(53)] = 960,
  [SMALL_STATE(54)] = 967,
  [SMALL_STATE(55)] = 974,
  [SMALL_STATE(56)] = 981,
  [SMALL_STATE(57)] = 988,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_string, 5, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cat_string, 5, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_value, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_value, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_curly_list, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_curly_list, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragrapth, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragrapth, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_curly_list, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_curly_list, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_string, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_string, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragrapth, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragrapth, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_string, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cat_string, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragrapth, 4, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragrapth, 4, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_string, 4, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cat_string, 4, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragrapth, 5, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragrapth, 5, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [184] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cat_string_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [187] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cat_string_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cat_string_repeat1, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_paragrapth_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragrapth_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [223] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_chimera(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
